### ISSUE TITLE
High dimensional multi-output regression

### ISSUE THREAD

**Issue by takafusui** [cornellius-gp/gpytorch#1000]
Hi,

I am a novice in GPyTorch, and I have two questions to regress a multi-output function in a high dimensional functional space.

1. N-dimensional function approximation
For instance in GPy, there is a straight forward way to approximate a 2D function: https://nbviewer.jupyter.org/github/SheffieldML/notebook/blob/master/GPy/basic_gp.ipynb#2-dimensional-example

How can I do the same task with GPyTorch? I found that the grid structured training data example: https://gpytorch.readthedocs.io/en/latest/examples/02_Scalable_Exact_GPs/Grid_GP_Regression.html
but my function has more than 10 dimensions; thus, I am reluctant to regress my function on the grid points.

2. Multi-output function regression in a high dimensional space
My function has multi-outputs. I know the tutorial on the Multitask GP regression: https://gpytorch.readthedocs.io/en/latest/examples/03_Multitask_Exact_GPs/Multitask_GP_Regression.html
How can I extend this example from a single to a high dimension?

Thank you in advance.

(Sorry in advance if I duplicate existing issues...)

**Comment by gpleiss** [comment]
1. How much data do you have, and do you have a GPU? If you don't have a GPU - maybe try the [SVGP multi-output example](https://gpytorch.readthedocs.io/en/latest/examples/04_Variational_and_Approximate_GPs/SVGP_Multitask_GP_Regression.html). If you have a GPU and n < 10,000, I would follow the multi-task example that you link to, and simply call `.cuda` on the model and inputs [see this example](https://gpytorch.readthedocs.io/en/latest/examples/02_Scalable_Exact_GPs/Simple_GP_Regression_CUDA.html). If you have a GPU and n > 10,000, either do SVGP or follow the [KeOPs tutorial](https://gpytorch.readthedocs.io/en/latest/examples/02_Scalable_Exact_GPs/KeOps_GP_Regression.html).

2. The multitask example that you link to is suited for multi-dimensional functions as well! If your training/testing inputs are `n x d` rather than `n`, this example should work right out of the box.

**Comment by takafusui** [comment]
Hi,

thank you for your very prompt replay!
Where should I tell GPyTorch that the shape of train/test inputs, let's say `train_x`, has the shape of `n x d`, not `n`?
For instance, in the multitask example, where should I modify the `MultitaskGPModel` to have `d` dimensions inputs?
```
class MultitaskGPModel(gpytorch.models.ExactGP):
    def __init__(self, train_x, train_y, likelihood):
        super(MultitaskGPModel, self).__init__(train_x, train_y, likelihood)
        self.mean_module = gpytorch.means.MultitaskMean(
            gpytorch.means.ConstantMean(), num_tasks=2
        )
        self.covar_module = gpytorch.kernels.MultitaskKernel(
            gpytorch.kernels.RBFKernel(), num_tasks=2, rank=1
        )

    def forward(self, x):
        mean_x = self.mean_module(x)
        covar_x = self.covar_module(x)
        return gpytorch.distributions.MultitaskMultivariateNormal(mean_x, covar_x)


likelihood = gpytorch.likelihoods.MultitaskGaussianLikelihood(num_tasks=2)
model = MultitaskGPModel(train_x, train_y, likelihood)
```

For the standard `class ExactGPModel`, where should I change to have `d` dimensions training data?

Thank you!!

**Comment by jacobrgardner** [comment]
You shouldn't need to change anything to use multidimensional data for either example. Just make `train_x` `n x d`., and keep `train_y` as `n x t` in the mutlitask case or `n` in the single task case.

**Comment by takafusui** [comment]
Thank you for your help. Now everything becomes fine! I appreciate the supportive environment.
