### ISSUE TITLE
[Question] Kronecker GP non-square grid

### ISSUE THREAD

**Issue by bwengals** [cornellius-gp/gpytorch#1048]
I think I'm missing something basic about how gpytorch treats grids under the hood, but I'm trying to adapt the [grid GP example](https://github.com/cornellius-gp/gpytorch/blob/master/examples/02_Scalable_Exact_GPs/Grid_GP_Regression.ipynb) to a non-square grid.  

Specifically, say my grid is 3d and the training data has dimensions n1 x n2 x n3.  I'd like to be able to use a *different* kernel for each dimension and exploit Kronecker structure.   Noise is just spherical Gaussian.  

So K train would look like, say:  

    K =  [k1(x1, x1') kron k2(x2, x2') kron k3(x3, x3')] + sigma2 I

where, `x1 = [0, 1, 2]`, `x2 = [(0, 0.0), (1, 0.1), (2, 0.2), (3, 0.3)]` and `x3 = [0, 1, 2, 3, 4]`, so K would be 60 x 60 (because `n1 = 3`, `n2 = 4`, `n3 = 5`, and `x2` has two input dimensions).

How do you use `GridKernel`, and the `grid` parameter to represent this?  Which likelihood and which distribution in the `forward` method should be used?   I think is very close to #319, but still no luck.  Let me know if I should give a code example of where I'm at.  Thanks in advance, excited to try out the package!

**Comment by jacobrgardner** [comment]
Hi @bwengals --

`GridKernel` as written is intended wrap a single base kernel. That being said, note that `GridKernel` as written already supports rectangular grids if you have a single base kernel -- just pass in a list of differently shaped grids.

If you want to do a Kronecker product of multiple base kernels, I'd either just accomplish this in the `forward` method of your model or in your own kernel. This won't be hard.

The high level idea of GridKernel is to call the kernel on the data you supply with the first grid point:
https://github.com/cornellius-gp/gpytorch/blob/48adbe00008a82b9f4b93adf408bbd123e489cf9/gpytorch/kernels/grid_kernel.py#L120-L123

Then we construct a `ToeplitzLazyTensor` out of covars -- this is because for a stationary kernel the covariance matrix of a 1D grid is Toeplitz. Finally, we construct a KroneckerProductLazyTensor over the different covars. A lot of the code complexity there is really just to handle arbitrary batch dimensions.

If what you want is a KroneckerProduct over three 1D grids, then you basically want to do something like:
```python
covar1 = ToeplitzLazyTensor(base_kernel_one(grid1_first_pt, x1))
covar2 = ToeplitzLazyTensor(base_kernel_two(grid2_first_pt, x2))
covar3 = ToeplitzLazyTensor(base_kernel_three(grid3_first_pt, x3))

final_covar = KroneckerProductLazyTensor(covar3, covar2, covar1)  # construct Kronecker product
```

If you'd like, one way to do this would be to make three `GridKernel`s in your model, and then in your model `forward` call construct `final_covar` by calling each of the grid kernels and then constructing your `KroneckerProductLazyTensor`. Then just return a `MultivariateNormal` with an appropriately sized mean and your `KroneckerProductLazyTensor` as the covariance matrix.

**Comment by bwengals** [comment]
Thank you for the response!  I think I understand. 

Is the `first_grid_point` is all you need to pass in to the kernel because of the Toeplitz structure?  Further down in `grid_kernel.py` I think the calculation happens without assuming Toeplitz structure:  https://github.com/cornellius-gp/gpytorch/blob/bd9a8b2765407d4d55127464836c2d17f24bc843/gpytorch/kernels/grid_kernel.py#L137-L139

Then, if I do what you suggest in the `forward` section of the model (not making a modified `GridKernel` class), will the prediction step still work the same?  (looking at `likelihood(model(x_test))` [here](https://github.com/cornellius-gp/gpytorch/blob/master/examples/02_Scalable_Exact_GPs/Grid_GP_Regression.ipynb)) 

Is there anywhere in the docs that explain a little bit about how predictions vs training is calculated under the hood?  I would like to implement this is the most "correct" way.  Thanks again.

**Comment by jacobrgardner** [comment]
`GridKernel` does abstract out `base_kernel` as a `Kernel` but it can't just be a list or like an arbitrary python object without some modifications. We'd need to see your modifications to help here most likely.

The two cases where we don't use Toeplitz structure are (1) when the setting for using it is off, which you would turn off generally when your grids are small since exploiting Toeplitz structure involves computing FFTs that are slower than standard O(n^2) matrix multiplies for small n, and (2) at test time when computing k(x_test, x_train).
