### ISSUE TITLE
[Docs] Simple regression example

### ISSUE THREAD

**Issue by vincent2303** [cornellius-gp/gpytorch#1061]
Hi,

I'm new on gpytorch and I'm having a problem with the simple regression example (https://gpytorch.readthedocs.io/en/latest/examples/01_Exact_GPs/Simple_GP_Regression.html).
The example works well but when I change the function that generates the training points, I have a weird behavior.

I changed the period of the sinus and I removed the noise, so I changed this line:
train_y = torch.sin(train_x * (2 * math.pi)) + torch.randn(train_x.size()) * math.sqrt(0.04)
 to :
train_y = torch.sin(train_x * (10 * math.pi))
the model means become 0.

First, I thought that it was because there is not enough training points so I added more training points and that's where it becomes weird. When I use 309 training points [ train_x = torch.linspace(0, 1, 309) ] , the mean fits perfectly the function but when I use 308 training points the mean become null...

Is there something I'm missing ?

Thank you.

**Comment by gpleiss** [comment]
Hi @vincent2303 there's two issues going on here:

1) When you're training, you're falling into a local minimum. The function you are learning has much higher frequency. If you start with the default initialization (lengthscale=0.69 or so), the lengthscale is too large to fit such a fast changing function. The model will converge to the local minimum where everything is considered to be (random) observational noise. If you add
```python
model.covar_module.base_kernel.initialize(lengthscale=0.01)
```
after you initialize the model, the initial lengthscale parameters will be more suited for the function you are trying to model. The hyperparameters converge to a much better optimium in this case.

2) When you say "the mean becomes null" - do you mean it reverts to a constant function with mean 0, or do you mean that the model outputs NaNs? If it's the former, then the previous point should address the issue. If it's the latter, the issue is that you are trying to fit a function with no observation noise. This is really difficult for GPs to fit, as kernel matrices with no observational noise are super ill conditioned and therefore very unstable. Keeping the ` torch.randn(train_x.size()) * math.sqrt(0.04)` in the example (or even multiplying by math.sqrt(0.001)) should make things a lot more stable.

Hope this helps!

**Comment by vincent2303** [comment]
Perfect, initializing the lengthscale to a smaller value fixed it. Thank you very much for the detailed answer.
