### ISSUE TITLE
How can we correctly parallelize multiple GPyTorch processes?

### ISSUE THREAD

**Issue by takafusui** [cornellius-gp/gpytorch#1106]
Hi,

I use GPyTorch to regress a multi-dimensional function and have realized that, without explicitly set by myself, GPyTorch (or maybe PyTorch?) tries to use as many CPUs as possible.
(Currently, I have no GPU...)
Is it a default behavior? If so, I am wondering what is the best practice to parallelize some GPyTorch processes on a desktop computer? In my scripts, I want to parallelize some parts, and my default choice is to use MPI, but I am afraid that MPI and GPyTorch might interface with each other...

**Comment by jacobrgardner** [comment]
Do you mean parallelizing separate GPs? This is most easily done by using our batch mode interface, e.g. [here](https://github.com/cornellius-gp/gpytorch/blob/master/examples/08_Advanced_Usage/Simple_Batch_Mode_GP_Regression.ipynb). Otherwise, I'd just run in separate processes.

Individual processes will use multiple cores because the underlying BLAS/LAPACK libraries do so. There are environment variables you can theoretically set to prevent this if you wanted to I suppose.

**Comment by takafusui** [comment]
Thank you for your comments. Yes indeed, this is due to the BLAS/LAPACK libraries. Thank you again.
