### ISSUE TITLE
[Docs] Errata in "Exact GP Regression with Multiple GPUs and Kernel Partitioning" example?

### ISSUE THREAD

**Issue by takafusui** [cornellius-gp/gpytorch#1114]
In the document of Exact GP Regression with Multiple GPUs and Kernel Partitioning, you coded:
```python
for i in range(n_training_iter):
            options = {'closure': closure, 'current_loss': loss, 'max_ls': 10}
            loss, _, _, _, _, _, _, fail = optimizer.step(options)

            print('Iter %d/%d - Loss: %.3f   lengthscale: %.3f   noise: %.3f' % (
                i + 1, n_training_iter, loss.item(),
                model.covar_module.module.base_kernel.lengthscale.item(),
                model.likelihood.noise.item()
            ))

            if fail:
                print('Convergence reached!')
                break
```
but according to the source code of PyTorch-LBFGS (line 486):
```python
fail (bool): failure flag
                    True: line search reached maximum number of iterations, failed
                    False: line search succeeded
```

You might treat the fail flag in a different way, or maybe am I wrong?
Thank you.

The example is found in:
https://gpytorch.readthedocs.io/en/latest/examples/02_Scalable_Exact_GPs/Simple_MultiGPU_GP_Regression.html

**Comment by jacobrgardner** [comment]
I think this is a reasonable use of the `fail` flag. If line search reaches the maximum number of iterations, it means that we were unable to find a point along the search direction that improved the function value. 

Given a deterministic function, this generally implies that we should stop optimizing given the settings that L-BFGS was run with, because if we ran another step we would encounter the same outcome.
