### ISSUE TITLE
covariance matrix and matrix multiplication

### ISSUE THREAD

**Issue by lerkoah** [cornellius-gp/gpytorch#114]
Hi,

I'm interesting in implement my own covariance matrix. I don't understand the forward step yet. But my covariance matrix have the form:

`K(i,j) = sum_k sum_ l W(k,i) K_{base}(k,l) W(l,j)`

If you want, you can write this as a matrix multiplication:

`K = W^T K_{base} W`
I have stored the matrix W in a numpy array.
Is it some way to implement this in gpytorch?

Regards,
Lerko.

**Comment by jacobrgardner** [comment]
If `W` is just a constant known matrix, you can convert it to a PyTorch tensor using `torch.from_numpy`, and then assuming you don't need sparse GP methods the easiest way to implement this is to simply perform the matrix multiplication in the `forward()` method of the GP model. For example, `forward` of `ExactGPModel` from the exact GP regression example notebook might now look like:

```python
    def forward(self, x):
        mean_x = self.mean_module(x)
        covar_x = self.covar_module(x)
        covar_x = self.W.t().matmul(covar_x.matmul(self.W))
        # Return model output as GaussianRandomVariable
        return GaussianRandomVariable(mean_x, covar_x)
```

assuming you passed in W as a `Tensor` to `init()`.

If you want to use the sparse GP methods, you'll need to make a `MatmulLazyVariable`. If `covar_x` is the output of `grid_interpolation_kernel`, you could do something like:

```python
covar_x = MatmulLazyVariable(self.W.t(), MatmulLazyVariable(covar_x, self.W))`
```

Hope this helps!

**Comment by lerkoah** [comment]
Thanks, I'm going to test this!

**Comment by lerkoah** [comment]
I tested the solution. The GP pass the train process, but not pass the test.
I introduced a sampling matrix H, that it has an 1 in the position i,j if the data[i] is observed trough data_observed[j]
that is means, if we have a vector [0, 1, 2, 3, 4] and we observed [0,1,3,4], then, the matrix H is:
```
1 0 0 0 0
0 1 0 0 0
0 0 0 1 0
0 0 0 0 1
```
This is the code:
```
    def forward(self, x):
        mean_x = self.mean_module(x)
        covar_x = self.covar_module(x)

        if self.training:
            covar_x = self.H.t().matmul(self.W.t().matmul(covar_x.matmul(self.W.matmul(self.H))))
        else:
            covar_x = self.W.t().matmul(covar_x.matmul(self.W))
        return GaussianRandomVariable(mean_x, covar_x)
```
For debuging, I'm trying to implement the [simple regression](https://nbviewer.jupyter.org/github/cornellius-gp/gpytorch/blob/master/examples/simple_gp_regression.ipynb) example, but using my Kernel.

In my case, I used 50 samplings for training, and then I want to infere the sames 50 points. An I getting this error:
```
RuntimeError: size mismatch, m1: [100 x 100], m2: [50 x 50] at /opt/conda/conda-bld/pytorch_1524584710464/work/aten/src/TH/generic/THTensorMath.c:2033
```

I think that in the testing gpytorch add the same 50 points to the gram matrix... is it ok?

Regards.

**Comment by jacobrgardner** [comment]
I am not totally sure I understand your use case but I do understand the problem you are running in to.

The challenge you have is that in GPyTorch during testing we call forward on the training and test data concatenated together.

If you have some static matrix W that is p x n, then during test time it'll be trying to multiply that by an (n+t x n+t) matrix. This isn't a problem unique to GPyTorch, in the sense that any GP software will need to get kernel matrices other than the n x n training one.

The solution depends on how you want to handle this. If you want W to just be multiplied by the training portion of the kernel matrix, then I would just special case that for testing by checking whether the model is train or eval mode, and only multiplying by the upper left n x n component of covar_x. You could probably also augment W in forward so that the dimensionality works out the right way. If you want W to somehow be multiplied by something involving the test data, then obviously it needs to change shape at test time anyways.

Ultimately, you need to prepare for covar_x to be n+t x n+t at test time.

Hope that helps!
