### ISSUE TITLE
PPGPR-MFD Implementation

### ISSUE THREAD

**Issue by Akella17** [cornellius-gp/gpytorch#1218]
I have the following doubts regarding the [MeanFieldDecoupledModel](https://docs.gpytorch.ai/en/latest/variational.html#batchdecoupledvariationalstrategy) example code(s):
1. Why would one need 3 independent PPGPR-MFD models? Is the output a 3 dimensional vector-valued GP?
2.  What's the difference between ```MeanFieldDecoupledModel``` with **shared hypers** and ```OrthogonallyDecoupledVariationalStrategy```?
3. Wouldn't we need two sets of inducing points for ```MeanFieldDecoupledModel```, like ```OrthogonallyDecoupledVariationalStrategy```?

**Comment by jacobrgardner** [comment]
Yeah those examples are just highlighting the semantics. I feel the first code example should be a simple non batch model; let me add that to the example notebook: https://github.com/cornellius-gp/gpytorch/blob/master/examples/04_Variational_and_Approximate_GPs/Modifying_the_variational_strategy_and_distribution.ipynb

The batch decoupling is a highly efficient special case where since the number of inducing points is kept the same (e.g. inducing_points should have a batch shape of 2 in the specified location), we can use batched linear algebra ops to make things a lot faster.

**Comment by Akella17** [comment]
@jacobrgardner Thanks for the quick response. Could you maybe answer my specific questions as well with some more details?

**Comment by gpleiss** [comment]
> What's the difference between MeanFieldDecoupledModel with shared hypers and OrthogonallyDecoupledVariationalStrategy?

OrthogonallyDecoupledVariationalStrategy ensures that the mean and variance inducing points are orthogonal with respect to the reproducing kernel Hilbert space. See https://arxiv.org/pdf/1809.08820.pdf, section 3.2. That ensures less redundancy between the mean/variance inducing points, but it is more restrictive.

> Wouldn't we need two sets of inducing points for MeanFieldDecoupledModel, like OrthogonallyDecoupledVariationalStrategy?

The two sets of inducing points are automatically created in the internals of `BatchDecoupledVariationalStrategy`.
