### ISSUE TITLE
Add proper support for priors

### ISSUE THREAD

**Issue by Balandat** [cornellius-gp/gpytorch#123]
While it's relatively straightforward to put priors on the hyperparameters (e.g. length scales, noise) by simply adding the appropriate log probabilities to the marginal_log_likelihood, this is not very user friendly.

There are some remnants of support for priors (e.g. https://github.com/cornellius-gp/gpytorch/blob/master/gpytorch/module.py#L101), but those don't seem to do anything.

We should add the ability to register a prior for a given parameter when registering that parameter (let's worry about joint priors over multiple parameters later). With the much improved distributions module in 0.4, I suggest we just use those Distribution objects directly for the priors.

Having first-class support for priors will also allow us to eliminate some funkiness with how the log-lengthscale bounds are being handled, by using an appropriate penalty prior that smoothly goes to zero at the boundary of the specified range.

**Comment by Balandat** [comment]
How do you feel about allowing to specify one of the two for each parameter:

1. a user-defined prior (basically conforming to a simple API that more or less only requires outputting a log_prob given a parameter value)
2. bounds (or log-bounds), which we then internally translate into a smoothed-out uniform prior with full support but rapidly decreasing values outside the bounds?

Also, would you agree that it is more intuitive to put a prior on the actual lengthscales, rather than the log-lengthscales?

**Comment by jacobrgardner** [comment]
The bounds in GPyTorch are at least partially a left over from back when we had lots of numerical stability issues that we didn't know how to deal with due to there not being a lot of prior work to draw from that exclusively used MVM based inference methods. As the package matured, we've mostly found much more clever solutions to many of these problems.

Therefore, another option to consider is removing bounds as a requirement entirely and making priors purely optional. Barring this option, your suggestion seems sensible to me.

I absolutely that it seems more natural to place priors on the parameters directly, especially since things like uniform priors have really strange implications in log space.  Do you have an interface in mind to deal with the fact that we register log parameters but define the prior over the parameters? Specifically, how when we define the prior do we specify whether the parameters being registered should be exponentiated or potentially whatever other transformation?

**Comment by jacobrgardner** [comment]
I think my recommendation just be to eliminate bounds entirely, and make priors a purely optional feature (with a smoothed uniform prior taking the place of bounds as an optional feature). Andrew pointed out (I think correctly) that hyperparameter priors are overwhelmingly used for BayesOpt compared to other GP applications.

Any lingering problems that bounds currently solved can probably be solved by good documentation suggesting priors in certain cases, and maybe even helpful error messages where, when we encounter NaNs that we know are caused by ridiculous hyperparameters, we suggest a prior.

**Comment by Balandat** [comment]
cc @darbour

**Comment by Balandat** [comment]
Done in #139
