### ISSUE TITLE
[Bug] AttributeError on import

### ISSUE THREAD

**Issue by fonnesbeck** [cornellius-gp/gpytorch#1244]
I've installed the latest release of GPyTorch on AWS, via pip. However, when I try to import `gpytorch`, I get an AttributeError having to do with the poutine submodule:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-8b7747befa0d> in <module>
----> 1 import gpytorch

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/gpytorch/__init__.py in <module>
      1 #!/usr/bin/env python3
----> 2 from . import (
      3     beta_features,
      4     distributions,
      5     kernels,

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/gpytorch/distributions/__init__.py in <module>
      9 try:
     10     # If pyro is installed, use that set of base distributions
---> 11     import pyro.distributions as base_distributions
     12 except ImportError:
     13     # Otherwise, use PyTorch

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/pyro/__init__.py in <module>
      2 # SPDX-License-Identifier: Apache-2.0
      3 
----> 4 import pyro.poutine as poutine
      5 from pyro.logger import log
      6 from pyro.poutine import condition, do, markov

AttributeError: module 'pyro' has no attribute 'poutine'
```

## System information

**Please complete the following information:**
- GPyTorch Version: 1.1.1
- PyTorch Version: 1.6.0
- Computer OS: AWS (Linux)

**Comment by jacobrgardner** [comment]
@fonnesbeck interesting -- are you trying to use Pyro in any way? It seems like it is installed in your environment, but is an insanely old version, which is causing the issue. I guess our two options for fixing this are:

1. Update pyro in your environment.
2. Make that except catch all exceptions, not just `ImportError`. However, I'm not sure if this is the best idea, since catching all possible exceptions is usually bad practice. We might be able to just add `AttributeError` there to handle old versions of pyro?

**Comment by fonnesbeck** [comment]
No, this occurs immediately after importing gpytorch following install. I am on Python3.6 on AWS; would this be the problem?

**Comment by jacobrgardner** [comment]
@fonnesbeck can you try to upgrade pyro-ppl in that environment and see if it fixes the issue?

**Comment by fonnesbeck** [comment]
Yeah, that worked. Thanks. Not sure why such an old version was installed in the first place, but its fixed now.
