### ISSUE TITLE
Some questions about scaling GPs to large data and high dimensions

### ISSUE THREAD

**Issue by dangthatsright** [cornellius-gp/gpytorch#1290]
Hello, I was wondering what my options were for scaling GPs to large data (1M) and high dimensions (1K).

If I wanted to use Exact GPs I suppose I could use [MultiGPU GPs](https://docs.gpytorch.ai/en/v1.1.1/examples/02_Scalable_Exact_GPs/Simple_MultiGPU_GP_Regression.html)
but I'd imagine this would also take a while due to the size of the kernel and multiGPUs are kinda expensive haha.

This prompts some approximate GPs:

I've seen [SGPR](https://docs.gpytorch.ai/en/v1.1.1/examples/02_Scalable_Exact_GPs/SGPR_Regression_CUDA.html) which under my understanding from #1123 is an approximate GP even though it is documented under the Scalable Exact GPs directory. I've tried this approach on a small dataset but I got 
`x1 should equal x2 in training mode` from the `InducingPointKernel` which I'm not sure what's going on. 
Even so, in the example you are passing in the whole dataset which I don't think will fit in memory once I go to 1M. Can this method be used with batch training? If so, don't you need a Variational Distribution.

Based on my understanding of training GPs with large data, I need to train in batch which requires a Variational Distribution, so I've tried [SVGP](https://docs.gpytorch.ai/en/v1.1.1/examples/04_Variational_and_Approximate_GPs/SVGP_Regression_CUDA.html). This method works for me, but has a couple downsides. 1. it becomes quite slow as I increase the number of inducing points from 1K to 5K. An Exact GP can handle 10k datapoints nicely so it's not due to blowup in kernel size - is it the variational calculations that's causing this slow down? Is there a way to get around it? 2. Seems like SVGP does a decent amount worse than Exact GP. Are there tips to make this better?

It seems like other options could involve using a structured kernel with additive/product structure. Do you recommend trying this out? Are there other approaches that could be used for scaling GPs?

**Comment by jacobrgardner** [comment]
In 1000 dimensions, variational inference is probably going to be your best bet, since it will let you use minibatch training. 

The thing that makes SVI slow with large numbers of inducing points is just the sheer number of times you have to do the operations. When training an exact GP, you do let's say 100 iterations of Adam. On 10k data points, you'll therefore invert a 10000x10000 matrix on the order of 100 times. In variational inference with m=5000 inducing points, you'll invert a 5000x5000 matrix, once *per minibatch*. If you have 1M data points and use a minibatch size of 1000, then each *epoch* of training will require you to invert that 5000x5000 matrix 1000 times, and if you do 20+ epochs of training, well... We have a method we are working on implementing that makes the scaling to m=5000 less painful.

By what metric is SVGP doing a lot worse on your data? Test error (e.g., mean performance) or test NLL (e.g., probabilistic performance)? There are a few potential fixes to either of these. Test error you might be able to fix by either using [deep GPs](https://github.com/cornellius-gp/gpytorch/blob/master/examples/05_Deep_Gaussian_Processes/Deep_Gaussian_Processes.ipynb) or deep kernels. Bad test NLL you might be able to use by switching to a [different loss](https://github.com/cornellius-gp/gpytorch/blob/master/examples/04_Variational_and_Approximate_GPs/Approximate_GP_Objective_Functions.ipynb) or using [DSPPs](https://github.com/cornellius-gp/gpytorch/blob/master/examples/05_Deep_Gaussian_Processes/Deep_Sigma_Point_Processes.ipynb)

**Comment by dangthatsright** [comment]
@jacobrgardner Thanks for the pointers! I will definitely check them out. I'm using average r2_score with cross validation but I think looking at NLL could be interesting.

In regards to the training time, your analysis makes sense and that's what I expect. I just ran this and with the ExactGP with 10k datapoints, each iteration of adam takes far less than a second (~0.2s). However, running with SVI and 5k inducing points, each iteration of adam takes ~5 seconds (using batch size of 2048). This is about 500x(? naively assuming time scales linearly with size of data) slower than I would expect. Any ideas why this may be the case? Looking forward to reading about the new implementation!

**Comment by jacobrgardner** [comment]
@dangthatsright Hmm, something certainly does sound very off -- a minibatch should take less time than an iteration of exact GP training, probably. Or at least, not be 25x slower.

Does this behavior occur in the example SVGP notebook when you set the relevant inducing point sizes?

**Comment by jacobrgardner** [comment]
Ah wait, no I understand -- with a batch size of 2048, you need to solve a `5000x5000` matrix against a `5000x2048` matrix, as opposed to a `10000x10000` matrix against a `10000x1` vector.

**Comment by dangthatsright** [comment]
Ah I see, that's starting to make some more sense. I'll read some more papers for the details. Thanks a bunch!
