### ISSUE TITLE
Does the default cg_tolerance make sense?

### ISSUE THREAD

**Issue by thjashin** [cornellius-gp/gpytorch#1304]
Hello,

I noticed that the default `gpytorch.settings.cg_tolerance` is set to 1 in GPyTorch.
I might get something wrong but does this even make sense? 
The cg implementation normalizes `rhs` before iterating, which means that 1 is used as the threshold for **relative** residual norms.
And if we plug in a zero solution, that relative residual norm will be 1. I must have missed something here..

Thanks,
Jiaxin

**Comment by gpleiss** [comment]
Hi Jiaxin,

This is a bit of a tricky point. You are right - that the initial solution of 0 would have a relative error of 1. However, we also run CG for a minimum of 10 iterations. Since the CG residual is non-monotonic (with respect to the 2 norm), it is often the case that the relative error goes above 1.

However - based on some experiments that @KeAWang , @jacobrgardner , and I have run - it may not be a bad idea to increase this tolerance to 0.1?

Also note that this only affects CG **training** for exact GPs, where exact solves are not too important. At test time, we use `gpytorch.settings.eval_cg_tolerance`, which is a tighter value.

(We are also working on a project to improve CG during training - stay tuned!)

**Comment by thjashin** [comment]
Geoff,

I see. Thanks. It is indeed a good point that the CG residual is non-monotonic w.r.t. 2 norm. Btw, I tried your msMINRES algorithm and it did work better when training variational GPs compared to CG, nice work!
