### ISSUE TITLE
[Question] Regularization of kernel covariance matrices

### ISSUE THREAD

**Issue by joacorapela** [cornellius-gp/gpytorch#1323]
Suppose I have training samples x very close to each other and I use a periodic kernel for GP regression. Then the kernel covariance matrix could not be invertible, which should compromise GP regression. I could not find in the documentation information about how GPyTorch deals with the problem of non-invertible kernel covariance matrices.

In Gardner et al 2019 GPyTorch: Blackbox Matrix-Matrix ... the authors state:

CG has a regularizing
effects which may improve methods involving the exact kernel over the Cholesky decomposition,
where numerical issues resulting from extremely small eigenvalues of the kernel matrix are ignored.
For example, Cholesky methods frequently add noise (or “jitter”) to the diagonal of the kernel matrix
for numerical stability. It is possible to reduce the numerical instabilities with double precision (see
Figure 2); however, this requires an increased amount of computation. BBMM on the other hand
avoids adding this noise, without requiring double precision.

From this it seems that GPyTorch does not need to regularize kernel covariance matrices. Is this a consequence of using conjugate gradient or of using preconditioning?

Thanks, Joaquin

**Comment by jacobrgardner** [comment]
So, this is true to an extent, but extremely poorly conditioned kernel matrices are hard to invert kind of no matter what you do. The point of that quote is that preconditioning definitely helps, and you can often get pretty far with very large preconditioners, even on matrices that Cholesky might give inaccurate solves for in fp32 or even outright fail on due to (because of machine precision) slightly negative eigenvalues.

A lot of the time unless you have extremely low noise settings, that doesn't really mean we shouldn't use jitter though. While the convergence rate of CG that's typically given in terms of the condition number is a loose upper bound, it's still the case that CG often converges more slowly for ill conditioned matrices.
