### ISSUE TITLE
[Documentation] No WhiteNoiseKernel?

### ISSUE THREAD

**Issue by tawe141** [cornellius-gp/gpytorch#1345]
In the [Exact GP Regression tutorial](https://docs.gpytorch.ai/en/v1.2.1/examples/01_Exact_GPs/Simple_GP_Regression.html), there's mention of a WhiteNoiseKernel, yet no such kernel currently exists. There was issue #113 and PR #152 regarding this, but it looks like it got removed at some point. Is there some alternative I should be using instead to add noise to my kernel?

**Comment by Balandat** [comment]
Yes, it existed at some point but has since been removed. This was usually used for adding known observation noise to the kernel itself. However, this really belongs into the likelihood, so we made a `FixedNoiseGaussianLikelihood` instead to achieve this: https://github.com/cornellius-gp/gpytorch/blob/e7583a0c44ca1631ba421d632cdb5086805f88d9/gpytorch/likelihoods/gaussian_likelihood.py#L100

We should update the tutorial...

**Comment by tawe141** [comment]
I see, thanks! It looks like `FixedNoiseGaussianLikelihood` isn't in the docs either. I can make a PR later in the week.

**Comment by gpleiss** [comment]
@tawe141 - I actually have an open PR for updating the likelihood docs. I'll get it merged soon :)
