### ISSUE TITLE
Code in variational_strategy.py

### ISSUE THREAD

**Issue by jbgao** [cornellius-gp/gpytorch#1402]
# 🐛 Bug

Dear Gpytorch Developers

Here is a possible issue with variational_strategy.py

I am wondering whether it is a special consideration or something missing.  According to the formula in Line 121, it seems an L is missing in front of self.prior_distribution.mean in Line 115.   I understand variable inducing_values has already included L.inv() according to whitening of the inducing posterior, but this is not the case for the prior.   It is fortunate that self.prior_distribution.mean is always 0, so no errors.

Thank you for the great package

J.

## To reproduce

** Code snippet to reproduce **
```python
# Your code goes here
# Please make sure it does not require any external dependencies (other than PyTorch!)
# (We much prefer small snippets rather than links to existing libraries!)
```

** Stack trace/error message **
```
// Paste the bad output here!
```

## System information

**Please complete the following information:**
- 
- 
-

**Comment by gpleiss** [comment]
Thanks for the catch - though the issue is not a missing L.

`self.prior_distribution` supplies the prior distribution of the **whitened inducing points**. The whitened inducing points `\tilde u` are given by the following deterministic transformation of the unwhitened inducing points `u`:

`\tilde u = K^{-1/2} ( u - \mu )`

where `K` and `\mu` are the prior covariance/mean of `u`.

The (predictive) posterior mean of an SVGP model evaluated at `x` is given by:

` k_x^T K^{-1} (m - \mu) + \mean_x `

where `k_x` is the cross-covariance between `x` and the inducing points, `\mean_x` is the GP prior mean evaluated at `x`, and `m` is the *unwhitened* inducing variational mean. By the deterministic transformation above, the whitened variational mean is equal to `\tilde m = K^{-1/2} (m - \mu)`. Therefore, we have that the (predictive) posterior mean is:

` k_x^T K^{-1/2} \tilde m + \mean_x `

In variational_strategy.py, `interp_term` is equal to `K^{-1/2} k_x`, and `inducing_values` is equal to `\tilde m`. Therefore, line 121 should be changed to:

```python
predictive_mean = (interp_term.transpose(-1, -2) @ inducing_values.unsqueeze(-1)).squeeze(-1) + test_mean
```

I'm putting up a PR to fix this.
