### ISSUE TITLE
[Question] Implementing multivariate Matern kernel

### ISSUE THREAD

**Issue by junmingguan** [cornellius-gp/gpytorch#1431]
Hi,

I am working on building a multioutput GP model, for which I need to implement a multivariate Matern kernel mentioned [here](https://projecteuclid.org/download/pdfview_1/euclid.ss/1433341471) at (10). More specifically, both the marginal covariances (over inputs) and the cross-covariances (inter-task) should be in Matern form, and I also want the freedom to specify different \nu's and lengthscales for different tasks (or inter-tasks).

As I was reading the docs I found that MultitaskKernel is relevant. But I am not sure if it offers the flexibility I mentioned above. I am wondering what would be the best way to implement such kernel. Should I somehow modify MultitaskKernel?

I am pretty new to GPytorch, and I would appreciate any help.

Many thanks in advance!
Jimmy

**Comment by gpleiss** [comment]
Sorry for the slow reply @junmingguan . You will probably have to implement your own kernel. See [this tutorial](https://docs.gpytorch.ai/en/latest/examples/00_Basic_Usage/Implementing_a_custom_Kernel.html) to get started.

In general, this makes for a better [Discussion topic](https://github.com/cornellius-gp/gpytorch/discussions) rather than an issue. I'm closing this issue for now, but re-open a discussion if you have further questions after viewing the tutorial.
