### ISSUE TITLE
Test Log Likelihoods

### ISSUE THREAD

**Issue by ssydasheng** [cornellius-gp/gpytorch#1461]
Hi,

I am recently playing around with KISS-GP models. From my codes, I observe KISS-GP outputs good RMSEs but much lower test log likelihoods compared to the SVGP models. I wonder if I am doing anything wrong and if anyone could help me with this. 

I started from the example in [KISS-GP-LOVE](https://github.com/cornellius-gp/gpytorch/blob/master/examples/02_Scalable_Exact_GPs/Simple_GP_Regression_With_LOVE_Fast_Variances_and_Sampling.ipynb) for the _elevation_ dataset, and put in the lines for computing log likelihoods, 

```
preds = model(test_x)
rmse = torch.mean((preds.mean - test_y)**2.)**0.5
lld = likelihood.log_marginal(test_y, preds).mean()
```
I compare the KISS-GP results with Table 1 in the [ExactGP](https://arxiv.org/abs/1903.08114) paper. 
 `KISS-GP: RMSE=0.383, LLD=-1.284`
 `ExactGP: RMSE=0.394, LLD=-0.619`
 `    SVGP       : RMSE=0.399, LLD=-0.519`

I also tested with another `3droad` dataset, starting from the example in [KISS-GP-KEOPS](https://docs.gpytorch.ai/en/latest/examples/02_Scalable_Exact_GPs/KeOps_GP_Regression.html).  I note that in the previous example, KISS-GP used deep kernel learning while others used a Matern kernel. For this dataset, both used a Matern kernel.
 `KISS-GP: RMSE=0.248, LLD=-1.243`
 `ExactGP: RMSE=0.101, LLD=-0.909`
 `    SVGP       : RMSE=0.481, LLD=-0.697`

I also share the colab scripts for replicating my experiments.
[elevation](https://colab.research.google.com/drive/1oJdyce6YGBpMkRBvMlFxLlzCN7KANXtE#scrollTo=YPia8LLvaSwu)
[3droad](https://colab.research.google.com/drive/1oJdyce6YGBpMkRBvMlFxLlzCN7KANXtE#scrollTo=YPia8LLvaSwu)

**Comment by gpleiss** [comment]
> I am recently playing around with KISS-GP models. From my codes, I observe KISS-GP outputs good RMSEs but much lower test log likelihoods compared to the SVGP models. I wonder if I am doing anything wrong and if anyone could help me with this.

This is a known phenomenon. See, for example, the results table in [this paper](https://arxiv.org/pdf/1903.08114.pdf). The lower log likelihoods could be due to a number of factors - such as a misspecified model prior. This is an active area of research, but it's likely that [SVGP's overestimation of the likelihood noise](https://arxiv.org/abs/1606.04820) might make the models more robust to model misspecification.

In the future, this would make for a better [Github Discussion](https://github.com/cornellius-gp/gpytorch/discussions) rather than an issue.
