### ISSUE TITLE
[Docs] Possible to fit a DeepGP without inducing points?

### ISSUE THREAD

**Issue by EvanBaker57** [cornellius-gp/gpytorch#1470]
Hi,

I'm just going through the examples in the documentation, which are very helpful, thanks :)

The examples for [variational GPs with non-Gaussian likelihoods](https://docs.gpytorch.ai/en/stable/examples/04_Variational_and_Approximate_GPs/Non_Gaussian_Likelihoods.html) show how to avoid inducing points while still performing variational inference via the UnwhitenedVariationalStrategy and by providing train_x instead of inducing_points in \_\_init\_\_.

On the other hand, the [DeepGP example](https://docs.gpytorch.ai/en/stable/examples/05_Deep_Gaussian_Processes/Deep_Gaussian_Processes.html) does not seem compatible with this work around, because you would need to provide the outputs of each layer for the layer above, which we don't have access to at the time of defining the functions? (except the bottom layer, which could still be provided train_x).

Is this something which can be done in GPyTorch at the moment? Would it even be practical to do if there were only a few hundred training points?

**Comment by gpleiss** [comment]
> On the other hand, the DeepGP example does not seem compatible with this work around, because you would need to provide the outputs of each layer for the layer above, which we don't have access to at the time of defining the functions? (except the bottom layer, which could still be provided train_x).

I can't think of a good way around this, and I'm not sure if there are any ideas from the DeepGP literature where people don't use inducing points. Of course, you can avoid inducing points in the first layer, but I think they're inevitable in the second layer.

One approach would be to use Hamiltonian Monte Carlo instead of VI for inference. This isn't supported right now in GPyTorch though.

**Comment by EvanBaker57** [comment]
Ah ok, thanks
