### ISSUE TITLE
beta value in VariationalELBO

### ISSUE THREAD

**Issue by irum** [cornellius-gp/gpytorch#1570]
Hi,
Beta = A multiplicative factor for the KL divergence term. Setting it to 1 (default) recovers true variational inference but if I set value greater than 1, let say 100 then what would be its effect?

**Comment by gpleiss** [comment]
Setting `beta` to 100 artificially inflates the effect of the prior. In other words, the variational posterior approximation will be closer to the prior. The opposite happens if `beta < 1`, which may be useful if the GP prior is likely misspecified.

Setting `beta` results in an optimization objective that isn't a true ELBO, but it is potentially useful depending on your problem.
