### ISSUE TITLE
Incremental GP training

### ISSUE THREAD

**Issue by sumitsk** [cornellius-gp/gpytorch#160]
Is it possible to train a GP in an incremental manner? For example, first train on 100 data points and then update the model parameters on the next batch of say 50 points instead of training from scratch on all 150 data points at one time?

**Comment by jacobrgardner** [comment]
If you literally just want to swap out the trianing data in a regression model, GP models have a `set_train_data` method which as of a PR yesterday have a `strict` argument you can set to False that allows you to change the size of your data. Something like:

```python
model = MyGPModel(orig_train_x, orig_train_y, likelihood)
...
# training code
...
model.set_trian_data(new_train_x, new_train_y, strict=False)
...
# continue training.
```

If you want to do something like minibatches, you'll need to use variational regression. We have an example of that using KISS-GP here: https://github.com/cornellius-gp/gpytorch/blob/master/examples/kissgp_variational_regression_cuda.ipynb, although it should work just as well with the standard `VariationalGP` instead of `GridInducingVariationalGP` if you only have 150 data points.

**Comment by jacobrgardner** [comment]
Hopefully this answered everything you needed -- reopen if you still have issues with this!

**Comment by MegaYEye** [comment]
Is it possible to update the parameters for only ``new_train_x`` and ``new_train_y``? I found training on whole data will be very costly.  However, if I do:
```
output = model(X[:10])
loss = -mll(output, y[:10])
```
In the training loop, a training error will show up: ``You must train on the training inputs!``
