### ISSUE TITLE
Can we implement user define loss function ?

### ISSUE THREAD

**Issue by Kangfei** [cornellius-gp/gpytorch#1694]
Hi,

Can we implement other regression loss for deep kernels?
For my project, due to the target value distribution, smooth L1 loss is the most suitable empirical loss function for my deep model. To transfer my deep model to deep kernel, can we implement the coresponding mll loss for the smooth L1 loss? It seems the ExactMarginalLogLikelihood corresponds to the MSE loss, so that whether other losses like L1 and smooth L1 can have a similar mll loss? If yes, how to implement that?

Best,
Kangfei

**Comment by gpleiss** [comment]
Hi @Kangfei for the future please post questions like this as a [Discussion topic](https://github.com/cornellius-gp/gpytorch/discussions) rather than an issue.

The optimization objective for GPs has to correspond to a probabilistic likelihood. The log likelihood under a GaussianLikelihood observation model roughly corresponds to MSE. You want to use a LaplaceLikelihood if you want a L1 log likelihood. Exact inference is not possible with a LaplaceLikelihood, so you will need to use one of the variational models.
