### ISSUE TITLE
Question regarding sampling from posterior

### ISSUE THREAD

**Issue by jdubkim** [cornellius-gp/gpytorch#1846]
Hi, I've been trying to generate samples from posterior distribution, but realised that my samples do not go through train datapoints.
<img width="409" alt="image" src="https://user-images.githubusercontent.com/18008640/144262455-45fe5bb5-ad88-4ca3-a96d-404394ab4e5b.png">
 
This is the code I used.
```python
class ExactGPModel(gpytorch.models.ExactGP):
    def __init__(self, train_x, train_y, likelihood):
        super(ExactGPModel, self).__init__(train_x, train_y, likelihood)
        self.mean_module = gpytorch.means.ConstantMean()
        self.covar_module = gpytorch.kernels.ScaleKernel(gpytorch.kernels.RBFKernel())
    
    def forward(self, x):
        mean_x = self.mean_module(x)
        covar_x = self.covar_module(x)
        return gpytorch.distributions.MultivariateNormal(mean_x, covar_x)

# initialize likelihood and model
likelihood = gpytorch.likelihoods.GaussianLikelihood()
model = ExactGPModel(train_x, train_y, likelihood)

test_x = torch.linspace(0, 1, 100)

model.eval()
likelihood.eval()

test_x.requires_grad_(True)

with torch.no_grad():
    observed_pred = likelihood(model(test_x))
    y_samples = observed_pred.sample()
```

But when I plot test_x and y_samples on the graph, I get the graph shown above, which is very different from samples from posterior distribution I saw from lectures and tutorials. 

<img width="597" alt="image" src="https://user-images.githubusercontent.com/18008640/144262843-e48a1309-7071-4e6e-8094-7b48332a075a.png">

Can someone help me to fix this problem? Thank you.

+) I read most of the documentations and tried to find resources on google which explains how to generate samples from posterior using gpytorch, but I couldn't find it. I might have missed something, but I couldn't resolve this issue by myself.

**Comment by gpleiss** [comment]
You should sample from the latent GP posterior (e.g. `model(test_x).sample()`). Right now you are sampling from the posterior predictive (`likelihood(model(test_x)).sample()`). The posterior predictive adds independent Gaussian noise to the latent posterior, which is why the sampled function looks so noisy.

Also, you should optimize the hyperparameters of the model - this will result in a better GP posterior fit.

In general, the samples do not need to go through the observations, because the observations are assumed to be noisy versions of the true latent function values.
