### ISSUE TITLE
[Bug] issue to compute SpectralMixtureKernel when tensors are loaded into cuda device

### ISSUE THREAD

**Issue by ivan-marroquin** [cornellius-gp/gpytorch#1886]
# 🐛 Bug

## To reproduce
Many thanks for making available such great package!

In order to reproduce this issue, I attached a Python script (see zip file).

** Stack trace/error message **
```
Traceback (most recent call last):
  File "test_issue.py", line 58, in <module>
    model= SpectralMixtureGPModel(support_x, support_label, likelihood)
  File "test_issue.py", line 24, in __init__
    self.covar_module.initialize_from_data(support_x, support_label)
  File "C:\Temp\Python\Python3.6.5\lib\site-packages\gpytorch\kernels\spectral_mixture_kernel.py", line 264, in initialize_from_data
    self.mixture_scales = torch.randn_like(self.raw_mixture_scales).mul_(max_dist).abs_().reciprocal_()
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```

## Expected Behavior

The SpectralMixtureKernel should be able to initialize the covariance from data, when the input tensors are loaded into cuda device

## System information

**Please complete the following information:**
-  1.6.0
-  1.10.0+cu102
-  Windows 10
-  3.6.5

## Additional context

[test_issue.zip](https://github.com/cornellius-gp/gpytorch/files/7873166/test_issue.zip)

**Comment by abdolrezat** [comment]
just a small note that your code doesn't train on cpu... but the error you refer to occurs when calling model.cuda() after you transformed the training inputs as cuda tensors and called the model. The reason is that here 
https://github.com/cornellius-gp/gpytorch/blob/61f643eb8b487aef332c818f661fbcdb1df576ca/gpytorch/kernels/spectral_mixture_kernel.py#L264
raw_mixture_scales have remained a cpu tensor while max_dist was transformed to cuda.
You can for example do all device changes after you created the model.

**Comment by ivan-marroquin** [comment]
Hi @abdolrezat 

Thanks for pointing my mistake. I made the suggested change, and the code worked as expected. This is not a bug.

Kind regards,
Ivan
