### ISSUE TITLE
Is there a feature that combines both categorical and continuous variable inputs in gpytorch 

### ISSUE THREAD

**Issue by promiseve** [cornellius-gp/gpytorch#2041]
Does this exist already?

**Comment by gpleiss** [comment]
Hi @promiseve sorry for the slow reply! I'm not sure exactly what you mean. Are you looking for a kernel that can operate on data that has both categorical and continuous features?

None of the kernels that we have implemented in GPyTorch are specifically designed for categorical features, though you could represent the categorical features as one hot vectors and use any of our default kernels on them.

Also, for the future, these kinds of questions should be posted as [discussions](https://github.com/cornellius-gp/gpytorch/discussions) rather than issues. I'm going to close this for now, but please open a discussion if you want to continue the conversation!

**Comment by Balandat** [comment]
We use a kernel of the form 

```
        K((x1, c1), (x2, c2)) =
            K_cont_1(x1, x2) + K_cat_1(c1, c2) +
            K_cont_2(x1, x2) * K_cat_2(c1, c2)
```
where `K_cont` and `K_cat` are kernels on the continuous and categorical variables, respectively, in BoTorch's `MixedSingleTaskGP` model: https://github.com/pytorch/botorch/blob/main/botorch/models/gp_regression_mixed.py#L28

**Comment by promiseve** [comment]
Good day,

Thanks for your contribution.

Regards,
Promise.
