### ISSUE TITLE
Multi-task likelihoods

### ISSUE THREAD

**Issue by Balandat** [cornellius-gp/gpytorch#213]
Multi-Task models currently do not allow for different noise levels for the different outputs. This is clearly something that we should support.

One way of doing this would be to implement a MultiTaskLikelihood Module that operates on the possibly generalized outputs of MultiTask models discussed in #209. 

IMHO, this suggests that in order to make things clean we should treat multi-output models (and hece the RandomVariable interface) as first-class citizens. @gpleiss, @jacobrgardner, @darbour, any thoughts?

**Comment by gpleiss** [comment]
This seems reasonable. I think we should have something similar to the ARD pattern we have for kernels. Modules should be able to have: 1) a singleton parameter, 2) a parameter for each dimension/task, 3) a parameter for each batch, or 4) a combination of 2 and 3.

Essentially, every model/module should be a batched/multi-output module, with an assumed batch size of 1 and output of size 1 unless otherwise specified.

**Comment by jacobrgardner** [comment]
Assuming the `nd x nd` covariance matrix is ordered so that all of the first task data is first, all of the second task data is second and so on, we'd basically want to form a `SumLazyVariable` out of the `KroneckerProductLazyVariable` we make now for the multi task kernel matrix, and another one that represents `I_{n} \kron diag(task_var)` where I_{n} is the `n x n` identity matrix and `diag(task_var)` -- basically the kronecker product of two `DiagLazyVariables`. Something like:

```python
covar_xi = gpytorch.lazy.KroneckerLazyVariable(covar_i, covar_x)
...
# Somewhere either in the model or a new likelihood
eye_lv = gpytorch.lazy.DiagLazyVariable(torch.ones(covar_x.size(-1), device=covar_x.device)
task_variances = gpytorch.lazy.DiagLazyVariable(torch.nn.Parameter(torch.zeros(covar_i.size(-1), device=covar_i.device))
covar_with_noise = covar_xi + KroneckerProductLazyVariable(eye_lv, task_variances)

return covar_with_noise
```

**Comment by gpleiss** [comment]
Minor point: the `nd x nd` covariance matrix will probably be ordered so that all `k` tasks for the first input come first, all `k` tasks for the second input, and so on. But yeah, that seems like a reasonable implementation.

What should the interface look like for specifying that we have want different parameters for the different tasks/batches?

**Comment by jacobrgardner** [comment]
I think this is where we may want the MultitaskKernel you mentioned earlier. If we do `kron(covar_i, covar_x)` like currently happens in the example notebook, then the non permuted version above holds (e.g., all of task 1 appears, then all of task 2). If we do `kron(covar_x, covar_i)` then it is messed up.

Basically, we need the ordering of `covar_x` and `covar_i` to match up with the ordering of `eye_lv` and `task_variances` which suggests this is something we absolutely shouldn't leave to the user.

With that in mind, we could have a `MultitaskKernel` and a `MultitaskLikelihood`? Or possibly a full `MultitaskModel` that extends exact gps?

**Comment by Balandat** [comment]
cc @rajkumarkarthik

**Comment by jacobrgardner** [comment]
Just chatted offline with Geoff, and I think I have a vision for this. I'll throw up a PR with a proposed implementation + interface of the new multitask stuff.

**Comment by Balandat** [comment]
Sounds great. FWIW, I've got some promising results for constrained batch EI using the Kronecker MTGP which is quite a bit more general than our current implementation, so having this would be great.
