### ISSUE TITLE
Sampling and its documentation is inconsistent

### ISSUE THREAD

**Issue by gbohner** [cornellius-gp/gpytorch#214]
Hi All, I'm relatively new to large-scale collaborative open source development, so please PM me if something should be done differently. I've been using pytorch for a project in the past few weeks, and it's great, but of course being in alpha there are quite a few inconsistencies. 

One of them is sampling of random variables:

1. Dimensions of sampled variables are inconsistent.
According to documentation in random_variables.py it should be ```n_samples * batch * dimension```, however in the most used case of GaussianRandomVariable it is ```batch * dimension * n_samples```, see in more detail in [point1](#point1).

2. Some types of random variables don't have batch mode. I think instead of adding batch mode for each, it would be reasonable to create a ```BatchRandomVariable```, see an example implementation in [point2](#point2), note that the sampling here conforms to the documented rather than the actual one for the moment.

3. Sampling is not implemented for some of the random variables, even though it should be easy, and it is a very generic way of using them. An example implementation for MixtureRandomVariable is in [point3](#point3).

#### Point1

```python
def sample(self, n_samples=1):
        """
        Draw samples from the random variable.
        n_samples - number of samples to draw (default 1)
        Returns: tensor of samples
        If the random variable is in batch mode, result will be
        s x b x d, where s is the number of samples, and b is the batch size
        and d is the dimensionality of the random variable
        If the random variable is not in batch mode, result will be
        s x ..., where s is the number of samples
        and d is the dimensionality of the random variable
        """
        raise NotImplementedError
```

Tests:

```python
b = 10 # Number of batch variables
d = 5 # Number of dimensions
n_samples = 20 # Number of samples
gauss_simple = GaussianRandomVariable(torch.randn(d,), (torch.rand(d,)+1e-6).diag())
gauss_batch = GaussianRandomVariable(torch.randn(b,d), torch.cat(b*[(torch.rand(d,)+1e-6).diag().unsqueeze(0)]))

gauss_simple.sample(n_samples).shape
 > torch.Size([5, 20])

gauss_batch.sample(n_samples).shape
 > torch.Size([10, 5, 20])
```

#### Point2

```python
class BatchRandomVariable(gpytorch.random_variables.RandomVariable):
    def __init__(self, *rand_vars, **kwargs):
        """
        Batch of random variables
        Params:
        - rand_vars (iterable of RandomVariables with b elements)
        """
        
        super(BatchRandomVariable, self).__init__(*rand_vars, **kwargs)
        if not all(isinstance(rand_var, RandomVariable) for rand_var in rand_vars):
            raise RuntimeError("Everything needs to be an instance of a random variable")
            
        self.rand_vars = rand_vars
        
    def representation(self):
        return self.rand_vars
    
    def mean(self):
        means = [rand_var.mean() for rand_var in self.rand_vars]
        return torch.Tensor(means, device=means[0].device)
    
    def var(self):
        variances = [rand_var.var() for rand_var in self.rand_vars]
        return torch.Tensor(variances, device=variances[0].device)
    
    def sample(self, n_samples=1):
        '''
        Sample n_samples for each of the b rand_vars and return an 
        n_samples x b x ... object consistent with random variables for which batch mode is enabled
        '''

        sample = torch.cat([rand_var.sample(n_samples).unsqueeze(0) for rand_var in self.rand_vars])
        return sample.permute(1,0, *range(2,sample.ndimension()))
```

#### Point3

```python
class MixtureRandomVariableWithSampler(gpytorch.random_variables.MixtureRandomVariable):
    def sample(self, n_samples=1):
        # Get representation
        rand_vars, weights = self.representation()

        # Sample from a categorical distribution
        sample_ids = torch.distributions.categorical.Categorical(probs=weights).sample((n_samples,))

        # Sample from the individual distributions
        samples = torch.Tensor([rand_vars[i].sample(1) for i in sample_ids], device=weights.device)

        return samples
```

**Comment by jacobrgardner** [comment]
Yeah a few of the older docstrings that have existed since the beginning of the package are bad or even outright wrong, you are definitely correct.

We are absolutely open to PRs fixing some of this, and it sounds like you already have some implementations that would be useful to have in the package! The MixtureRandomVariable sample routine in particular is something that probably never got implemented just because we never immediately needed it, but your implementation is correct and would be a nice thing to have in. Regarding BatchRandomVariable, I agree we should support it across the board, but it might be nicer to have the individual `RandomVariables` be responsible for batch mode (see e.g. `DirichletRandomVariable` which operates in batch mode only if `alpha` is a .batch).

That being said, it's worth noting that something on the todo list is to have the `RandomVariables` more closely integrate with the new(ish) `torch.distributions` package. In particular, `GaussianRandomVariable` is the only one we currently use that actually has custom functionality beyond what is exposed by the standard pytorch distributions. Therefore, a longer lived version of the PR might look more like using the `torch.distributions` functionality for sampling, which should work in batch in most cases I think?

**Comment by Balandat** [comment]
Note also how this relates to the discussion about multi-task outputs in #213

**Comment by gpleiss** [comment]
@gbohner we're going to move the RandomVariable classes to use/become PyTorch distributions. Then, our sampling will be consistent with the way sampling is implemented in PyTorch.

See #126
