### ISSUE TITLE
Unify `MultitaskGaussianLikelihood` and `_MultitaskGaussianLikelihoodBase`

### ISSUE THREAD

**Issue by Turakar** [cornellius-gp/gpytorch#2294]
Currently, there are two classes in [`multitask_gaussian_likelihood.py`](https://github.com/cornellius-gp/gpytorch/blob/562696432f2e4d481394f9556586c1c02152e466/gpytorch/likelihoods/multitask_gaussian_likelihood.py):

- `MultitaskGaussianLikelihood`, which is the class exposed in the public API
- and its superclass `_MultitaskGaussianLikelihoodBase`

`MultitaskGaussianLikelihood` is the **only sublcass** of `_MultitaskGaussianLikelihoodBase` according to PyCharm's inspection and a quick ripgrep search. Additionally, it does not override any functions of `_MultitaskGaussianLikelihoodBase` except for `__init__()`. As such, I would recommend to move `_MultitaskGaussianLikelihoodBase` into `MultitaskGaussianLikelihood` to simplify the hierarchy.

To make things worse, `MultitaskGaussianLikelihood.__init__()` calls `super(Likelihood, self).__init__()`, bypassing the code of `_MultitaskGaussianLikelihoodBase.__init__()`, which makes this **dead code**.

As `_MultitaskGaussianLikelihoodBase` is not part of the public API, this should be a non-breaking change.

**Comment by Balandat** [comment]
Some context here: Both `_GaussianLikelihoodBase` and `_MultitaskGaussianLikelihoodBase` are meant to enable more general noise models than in the respective `GaussianLikelihood` and `MultitaskGaussianLikelihood` classes. 

You can see the usage of `_GaussianLikelihoodBase` in BoTorch for implementing a heteroskedastic GP model that uses a general noise model rather than a `HomoskedasticNoise` model: https://github.com/pytorch/botorch/blob/main/botorch/models/gp_regression.py#L425

The idea of the `_MultitaskGaussianLikelihoodBase` setup is the same, but we haven't gotten to implement this in OSS yet. I guess it's not great that we use the "non-public" API in botorch and I'd be happy if things were mad public / cleaned up / refactored, but we should retain the functionality of this setup.

**Comment by Turakar** [comment]
Ok. I see that `MultitaskGaussianLikelihood` is not using the `Noise` API for its noise, but creates a custom noise setup, which forces it to not call `_GaussianLikelihoodBase.__init__()`. Is there are reason for that, too?

**Comment by Balandat** [comment]
Hmm I'm not entirely sure, it's been a long time since I looked at this code. Certainly the idea was that we use the noise model setup there as well; we may have never gotten to implement it and just worked with a custom setup in the meantime.

**Comment by Turakar** [comment]
Ok, I'll leave it up to you to decide whether there's anything one should do about this. As the initial matter of this issue seems to be resolved, I will close this for now.
