### ISSUE TITLE
[Bug] MultivariateNormal samples using Lanczos decomposition look wrong.

### ISSUE THREAD

**Issue by logan-dunbar** [cornellius-gp/gpytorch#2308]
# 🐛 Bug

Strange behaviour when generating samples from `MultivariateNormal` when using the Lanczos decomposition vs. `DiagLinearOperator` or Cholesky decomposition. I create a zero mean diagonal covariance MVN three ways (the size triggers Lanczos/Cholesky), and then sample from it, and receive very different looking samples. The Lanczos sample looks incorrect, the small and large `x` values should have larger variance.

## To reproduce

```python
import torch as t
import matplotlib.pyplot as plt
from linear_operator.operators import DiagLinearOperator
from gpytorch.distributions import MultivariateNormal

t.manual_seed(0)
x_1000 = t.linspace(0, 10, 1000)
x_500 = t.linspace(0, 10, 500)

omega_1000 = -0.5 * t.exp(-1 * ((x_1000 - 3.5) ** 2 / (1.4 ** 2)) ** 2) + 0.7
omega_500 = -0.5 * t.exp(-1 * ((x_500 - 3.5) ** 2 / (1.4 ** 2)) ** 2) + 0.7
omega_dist_1 = MultivariateNormal(t.zeros_like(x_1000), DiagLinearOperator(omega_1000 ** 2))
omega_dist_2 = MultivariateNormal(t.zeros_like(x_1000), t.diag(omega_1000 ** 2))
omega_dist_3 = MultivariateNormal(t.zeros_like(x_500), t.diag(omega_500 ** 2))

samples = 3
fig, axes = plt.subplots(1, samples + 1, figsize=(15, 4))
axes[0].plot(x_1000, omega_1000 ** 2, label=r'$\omega_{1000}^2$')
axes[0].plot(x_500, omega_500 ** 2, label=r'$\omega_{500}^2$')
axes[0].legend()
for i in range(samples):
  axes[i+1].plot(x_1000, omega_dist_1.sample(), label='DiagLO sample')
  axes[i+1].plot(x_500, omega_dist_3.sample(), label='Cholesky sample')
  axes[i+1].plot(x_1000, omega_dist_2.sample(), label='Lanczos sample')
  axes[i+1].legend()
plt.tight_layout()
plt.show()
```
![mvn_error](https://user-images.githubusercontent.com/5948302/226893276-158af433-ebbc-4f4c-8c59-0b966cdb52bd.png)

## Expected Behavior

I expect the distributions to produce samples that have the same distribution.

## System information

**Please complete the following information:**
- GPyTorch Version - 1.9.1
- PyTorch Version - 1.12.1+rocm5.1.1
- Computer OS - 5.13.0-52-generic 20.04.1-Ubuntu

**Comment by gpleiss** [comment]
The example you've created is adversarially difficult for Lanczos. Lanczos forms a low rank approximation of a matrix, and then uses this low rank approximation to draw an MVN sample. A low rank approximation is generally useful (and desirable) for Gaussian processes; if your GP does not have this low rank structure then your model won't be very useful!

Your covariance matrix example is a diagonal covariance, which cannot be well approximated by a low rank matrix. However, it's rare that our posterior covariance will ever be near diagonal (that basically means that the function we are trying to model is white noise; just like what you observe).

So yes, there are differences, and they are expected since Lanczos sampling is inherently an approximation.

**Comment by logan-dunbar** [comment]
Thanks for the detailed explanation. I guess I would just say that I was not expecting this behaviour, because I did not explicitly tell it to use the Lanczos approximation, and other users might also wonder about this. I had to dig quite deep to find that the value `settings.max_cholesky_size` is what controls the particular root decomposition in the `_choose_root_method` of `LinearOperator`. Thanks again, will be more careful from now on!
