### ISSUE TITLE
White noise kernel variance

### ISSUE THREAD

**Issue by sumitsk** [cornellius-gp/gpytorch#252]
This is more of an implementation doubt rather than an issue. In the forward method of white_noise_kernel, when the module is in eval mode, shouldn't the elif condition return zero instead of training variances? Shouldn't white noise variance be training variance when x1 = x2 = training data?  

https://github.com/cornellius-gp/gpytorch/blob/1b809b3c9570d617cb26949e40b921b36e826580/gpytorch/kernels/white_noise_kernel.py#L29-L37

**Comment by jacobrgardner** [comment]
The intention of the `elif` is so that when you compute for example the predictive mean you get something like:

`\mu = k_{*x}(K_{xx} + s*I + D_{wn})^{-1}y`

which I think is correct given that this is happening at the kernel level. An alternative implementation of this we are considering is a `WhiteNoiseLikelihood` where the noise is added at the likelihood level. This would mean that the training variances aren't necessarily added if the training data is passed as test data (which *is* done if the variances are handled at the kernel level instead of the likelihood level).

Perhaps a clearer implementation of this would be to have `WhiteNoiseKernel` initialized with the training data, and then `forward` can directly check for equality?

**Comment by jacobrgardner** [comment]
(See also #235)

**Comment by jacobrgardner** [comment]
As of @Balandat's PR adding support for Heteroscedastic likelihoods, WhiteNoiseKernel is no longer the preferred way of handling known variance observations. I'm closing this in favor of the real issue to be resolved around this, which is a need to add examples for the new interface (#395).
