### ISSUE TITLE
Scalable GPR with KISSGP error

### ISSUE THREAD

**Issue by sumitsk** [cornellius-gp/gpytorch#341]
Running Deep Kernel Learning GP regression [notebook ](https://github.com/cornellius-gp/gpytorch/blob/master/examples/05_Scalable_GP_Regression_Multidimensional/KISSGP_Deep_Kernel_Regression_CUDA.ipynb) throws RuntimeError: 
```
RuntimeError("The kernel should only receive the inducing points as input"). 
```

This happens in the 2nd iteration. In the first, the loss is a huge negative number of the order 10^16.

**Comment by jacobrgardner** [comment]
@sumitsk Should be fixed!

@Balandat I think this might have been related to #334. In the process of bisecting on this, I went back really really far in history (like before the beta release even) and the notebook with the optimizer as set still failed using pytorch-nightly but not with pytorch-0.4. 

I'm going to close this for now since I was able to reproduce and then fix the issue, but I will note that I've had to change a lot of learning rates recently to get notebooks that previously worked working again on pytorch-nightly. Anything on the pytorch side that might have caused this?

**Comment by Balandat** [comment]
I am not sure. I tried to bisecting this but it has been very challenging, because the failures weren't deterministic and only showed up occasionally, so it's hard to automate this.

I can ask the pytorch gurus about this - let's make sure we can narrow this down before I do, if I understand you correctly this is b/c the Adam/SGD optimizers are behaving differently for the same settings / initial conditions?

**Comment by sumitsk** [comment]
@jacobrgardner , @Balandat . I tried running the updated notebook but I keep getting RuntimeError: 
```
Lapack Error sysev: 14 off-diagonal elements didn't converge to zero at ..... 
```
I have seen this error occur occasionally but on this particular setup, it is in every run!!

**Comment by jacobrgardner** [comment]
@sumitsk This could be useful to help us understand what's going on. I just checked, and the notebook runs through fine for me, even with various different settings of the learning rate / number of training iterations.

What does your setup look like? I am running gpytorch master against pytorch `1.0.0.dev20181102 py3.7_cuda9.2.148_cudnn7.1.4_0`.

**Comment by jacobrgardner** [comment]
Just to be safe, I pushed the two DKL `elevator` dataset notebooks again.

**Comment by sumitsk** [comment]
@jacobrgardner . On the latest torch-nightly `1.0.0.dev20181103`, the notebook runs properly. Closing this now.
