### ISSUE TITLE
Deprecate log space parameters in favor of softplus

### ISSUE THREAD

**Issue by jacobrgardner** [cornellius-gp/gpytorch#386]
I’m getting very good feedback from a bunch of people using softplus in place of exp to enforce positivity constraints on some of the hyperparameters. It appears to require very little tweaking of optimization hyperparameters, and significantly improves model robustness and performance.

#383 lets us gracefully deprecate `log_*` parameters in favor of this in a way that we should be able to preserve model loading, calls to `model.covar_module.log_lengthscale = ...` and others. Given these two factors (strong empirical benefits, relatively easy code transition), I am now in favor of putting this in for 0.1.0.

@gpleiss are you on board for a 0.1.0 release given that we can gracefully deprecate `log` parameters now, or would you still prefer 0.2.0 for the switch?

**Comment by jacobrgardner** [comment]
I think @samuelstanton has some concrete examples of the difference this makes

**Comment by gpleiss** [comment]
We should absolutely do a 0.2.0 release for this feature. This will be a breaking feature for models that people have saved. And since this is a breaking change that would affect the most commonly used models in GPyTorch, we should absolutely follow semantic versioning here.

That being said, I wouldn't be opposed to doing a 0.2.0 release before NIPS, and we could save the batch-mode stuff for a 0.3.0 release.
