### ISSUE TITLE
Docs check Travis CI is still on python 3.5.6

### ISSUE THREAD

**Issue by KeAWang** [cornellius-gp/gpytorch#580]
Even though officially gpytorch requires Python >=3.6, our docs check Travis CI is still on python 3.5.6 which causes it to fail on python 3.6 features like f-strings. (Example: https://travis-ci.org/cornellius-gp/gpytorch/builds/507316021?utm_source=github_status&utm_medium=notification)

**Comment by jacobrgardner** [comment]
I would be fine dropping support for python 3.5 since we do technically already say we require 3.6 or above.

The reason we build against 3.5 right now is because of our config for readthedocs. It turns out you actually can have readthedocs use py3.6 or py3.7:

https://docs.readthedocs.io/en/latest/config-file/v1.html?highlight=3.6

So we would just need to do that.

**Comment by gpleiss** [comment]
Just stressing what @jacobrgardner says - if we do drop 3.5 support, we need to be extremely careful that we don't break the docs. readthedocs tends to fail silently. We've had our docs down for several weeks before because we included an f-string and got no notifications from readthedocs.

**Comment by jacobrgardner** [comment]
Docs on Travis and RTD now build on py36.

Corollary: we can start using type hints
