### ISSUE TITLE
offset in linear kernel does not appear to update

### ISSUE THREAD

**Issue by Duane321** [cornellius-gp/gpytorch#590]
Hey so, there appears to be an issue with the offset hyperparameter for the linear kernel. This is easiest to see if we look at issue [#559]. If you run that _now_, we actually get offset terms that remain all zero:

![image](https://user-images.githubusercontent.com/19956442/54737325-93384380-4b6c-11e9-99a1-be9eac25d89c.png)

If you look at that original issue, we didn't see this results then.

**Comment by jacobrgardner** [comment]
@Duane321 Yes this is somewhat intentional unfortunately. We've killed the `offset` parameter of the linear kernel to bring our definition of the linear kernel in line with other implementations of it (e.g. gpflow / gpy / sklearn / gpml), which we feel make for easier comparisons (and users can still register an offset to the GPModel itself and subtract in `forward` if they want one).

The parameter still exists as a way to soft deprecate it so that model loading isn't broken. Now that I think about it with some distance and clarity on the issue, a better solution would probably be to override the default pytorch module's state dict loading to throw out the offset parameter on load, and ditch the parameter in the linear kernel.

**Comment by jacobrgardner** [comment]
Okay, offset no longer exists even as a means of soft deprecation anymore!
