### ISSUE TITLE
psd_safe_cholesky unstable (RuntimeError: MAGMA potrf)

### ISSUE THREAD

**Issue by Akella17** [cornellius-gp/gpytorch#626]
Almost always, after receiving a couple of warning regarding added jitters to the diagonal, I get a runtime error (MAGMA potrf) in line 21 of ```gpytorch/utils/cholesky.py```. To reproduce this issue, you can run the ```GP-AC_Exact.ipynb``` in the shared link (https://drive.google.com/drive/folders/1aNgAfSSCTmMAUxf-1emYbe613O47KiIZ?usp=sharing).

> RuntimeError: MAGMA potrf : A(106,106) is 0, A cannot be factorized at /pytorch/aten/src/THC/generic/THCTensorMathMagma.cu:597

**Comment by Akella17** [comment]
I am using DKL GP regression (w/KISS-GP) module with the extracted features scaled down to [-1, 1] range before feeding it to GP.
```projected_x = gpytorch.utils.grid.scale_to_bounds(projected_x, -1, 1)```

Is scaling the inputs to [-1,1] not sufficient? Or should I have to calculate the moving averages of mean and std to normalize the extracted features?

**Comment by gpleiss** [comment]
Here are my thoughts on this:

- Try using a smaller learning rate or a different optimizer. When these errors occur (especially with DKL models), it is likely that your optimizer is ending up in a regime with bad parameters. (This issue is not unique to DKL/GPyTorch.)
- Try training an exact GP without an approximate kernel. This will tell you if the issue if with your modeling choices, or with the kernel approximation you are using.
- Try using batch normalization to improve the stability of your feature extractor.
- Update your model to use the latest PyTorch/GPyTorch conventions. For example, I see you are still using `torch.autograd.Variable`, which has been deprecated for a while now.
