### ISSUE TITLE
Question regarding heteroskedastic noise

### ISSUE THREAD

**Issue by Duane321** [cornellius-gp/gpytorch#653]
Hey GPyTorch team,

Hope you are all getting a lot out of GPyTorch - I know I certainly am!

My question regards kernel design: I'm hoping to increase the variance of a few test data points without changing my point predictions for those points too much. From looking through the available kernels, I can't see any obvious way to make this behavior happen.

I'll provide my best guess. Let's say I have some kernel defined and I'd like to change it to have this behavior. I could apply a multiplication by a linear kernel that resolves to 1 whenever the data points _isn't_ one of those special test points. Otherwise, it's some large number (maybe 2). So far I haven't had much luck with this, but I think I could just be screwing up the optimization. This also does impact the point prediction, but that might be unavoidable. I'm hoping that the variance parameter on the linear kernel gives me my increase in the prediction interval around this test point.

Do you think I'm on the right path? Do you have recommendations?

Any words are appreciated,
DJ

**Comment by jacobrgardner** [comment]
One way to accomplish this might be to use a FixedNoiseGaussianLikelihood:
https://github.com/cornellius-gp/gpytorch/blob/5b0425fd5c6c2f16d60a591a5bbaedc98d4b4382/gpytorch/likelihoods/gaussian_likelihood.py#L102-L110

In the last line of this example, a supplied vector of noises are added to the test predictions. This won't affect the point predictions at all, because it effectively amounts to inflating the variance of the test points, while the test means remain unchanged.

Is this roughly what you are looking for, or am I misunderstanding something?

**Comment by Duane321** [comment]
oh this is perfect! I didn't realize that FixedNoiseGaussianLikelihood allows for different noises for different test points. 

As always, thanks for the help Jacob

**Comment by jacobrgardner** [comment]
No problem! `FixedNoiseGaussianLikelihood` is pretty new, and we have so much documentation to catch up on we don't have example notebooks for that yet, just the docstrings demonstrating it.

**Comment by eytan** [comment]
@jacobrgardner, @Balandat, I wonder if the name `FixedNoiseGaussianLikelihood` is a little misleading, as `FixedNoise` (at least on the surface) sounds like a homoskedastic noise model.  Perhaps something like `KnownNoise` would be a little less subject to this misinterpretation?

**Comment by Balandat** [comment]
sounds reasonable to me, I'll let @jacobrgardner decide if he wants to make that change.
