### ISSUE TITLE
Remove Woodbury formula from preconditioner computation

### ISSUE THREAD

**Issue by jacobrgardner** [cornellius-gp/gpytorch#709]
Now that PyTorch master has support for batch mode QR, we should finish removing usage of the Woodbury formula and only rely on the QR decomposition, which is significantly more numerically stable.

The following two else branches should disappear:
https://github.com/cornellius-gp/gpytorch/blob/de92cbc6cf5127a9b688bd47ead681d642acf45d/gpytorch/lazy/added_diag_lazy_tensor.py#L97-L104
and:
https://github.com/cornellius-gp/gpytorch/blob/de92cbc6cf5127a9b688bd47ead681d642acf45d/gpytorch/lazy/added_diag_lazy_tensor.py#L117-L124

**Comment by esass10** [comment]
Hi, can I be assigned this issue? I am very interested

**Comment by Balandat** [comment]
Hmm I believe this issue is not current anymore? Note that all the lazy tensor logic has long moved into the `linear_operator` package, it now lives here: https://github.com/cornellius-gp/linear_operator/blob/main/linear_operator/operators/added_diag_linear_operator.py#L96 (but is already using the batch QR decomposition).
