### ISSUE TITLE
Confusion with multitask GP parameters

### ISSUE THREAD

**Issue by SLSC94** [cornellius-gp/gpytorch#715]
Hi, I'm trying to implement a multi-task (4 tasks) GP, and I'm looking at the (non-mean) parameters that the model has. I'm slightly baffled about what the model is outputting when I run:
```
for name,param in model.named_parameters():
    if 'means' not in name:
       print(name)
       print(param)
       print(' ')
```
With the corresponding output:
```
likelihood.raw_noise
Parameter containing:
tensor([-4.2385], requires_grad=True)
 
likelihood.noise_covar.raw_noise
Parameter containing:
tensor([-4.3324, -4.2683, -4.2212, -4.1200], requires_grad=True)
 
covar_module.task_covar_module.covar_factor
Parameter containing:
tensor([[-1.8862],
        [-0.1288],
        [-1.5933],
        [-1.7035]], requires_grad=True)
 
covar_module.task_covar_module.raw_var
Parameter containing:
tensor([-2.0250,  1.2220, -2.0172, -1.8875], requires_grad=True)
 
covar_module.data_covar_module.raw_lengthscale
Parameter containing:
tensor([[-1.0075]], requires_grad=True)
```
I have two questions: 

1) What is the difference between the parameters `likelihood.noise_covar.raw_noise` and `covar_module.task_covar_module.raw_var` ? In the [original paper](https://papers.nips.cc/paper/3189-multi-task-gaussian-process-prediction.pdf) on Multi-task GP learning, I understand that there should only be one (diagonal 4 x 4) matrix D that accounts for the noise in the data, but why does there seem to be two in this case?

2) How are negative values interpreted for the covariances? Do we exponentiate them?

Thank you for your help and for developing this package!

**Comment by jacobrgardner** [comment]
Hi @SLSC94,

1. The full kernel will be something like `K_{data} \kron (covar_factor * covar_factor^{T} + diag(softplus(raw_var))`, to which `softplus(raw_noise)` is added as a diagonal component. In some sense,  the `raw_var` parameter captures the task dependent noise. The likelihood noise is indeed somewhat redundant, but is important because it distinguishes between observations `y` and the latent function `f`.

2. Keep in mind that the `covar_factor` is actually the square root of the task covariance matrix, so (a) negative values here do not necessarily imply negative values in the task covariance matrix, and (b) negative values in covariance matrices are actually totally okay! Just because many popular kernels are strictly positive (e.g. RBF/Matern) doesn't mean it's not okay to have negative values in off diagonal elements of covariance matrices :-).

**Comment by SLSC94** [comment]
Ah, thank you so much for your reply! I understand it now (: This library is truly a lifesaver!
