### ISSUE TITLE
How to access the internals of a KISS-GP kernel?

### ISSUE THREAD

**Issue by Akella17** [cornellius-gp/gpytorch#736]
GP layer inputs: (s<sub>i</sub>,z<sub>i</sub>)
Kernel (KISS-GP): k<sub>rbf</sub>(s,s') + k<sub>linear</sub>(z,z')

What is the right approach to design this kernel:
1) KISS_GP(Additive_Kernel(RBF( s, s'), Linear( z, z')))
2) Additive_Kernel(KISS_GP(RBF( s, s')), KISS_GP(Linear( z, z')))

Also, how can I get the list of **virtual** inducing points (virtual because the inducing points needn't lie in the training data) used to create the K<sub>UU</sub> covariance matrix. Further, I also need the &alpha;<sub>t</sub> vector and C<sub>t</sub> matrix (these shall be used to compute the posteriors of other (derived) GPs).

&alpha;<sub>t</sub> = [K<sub>X,X</sub> + &sigma;<sup>2</sup>I]<sup>-1</sup> y
C<sub>t</sub> = [K<sub>X,X</sub> + &sigma;<sup>2</sup>I]<sup>-1</sup>

Where originally, posterior mean = K<sub>X*,X</sub> &alpha;<sub>t</sub> and posterior covariance = K<sub>X*,X*</sub> - K<sub>X*,X</sub> C<sub>t</sub> K<sub>X,X*</sub> @jacobrgardner @gpleiss

**Comment by jacobrgardner** [comment]
KissGP can't be applied to the linear kernel is not stationary. However, because the linear kernel is inherently low rank, you don't need a sparse GP method around it to get speed. Just do an 
```
AdditiveStructureKernel(GridInterpolationKernel(RBFKernel(...)) + LinearKernel(...)
```
or 
```
AdditiveStructureKernel(GridInterpolationKernel(RBFKernel(...)) + AdditiveStructureKernel(LinearKernel(...))
```
respectively. In general for SKI we don't explicitly store the full set of virtual inducing points because it is exponentially large in d and, while we can't avoid the exponential running time without SKIP, we don't also need to pay exponential memory. However, if you really want, you can get the 1D pre-Kronecker representation of the grid with `my_grid_kernel.grid`.

`\alpha_t` you can get by calling your kernel and doing `covar_x.inv_matmul(train_y)`. Alternatively, you can do `model.prediction_strategy.mean_cache` if you've already made predictions with your model.

`C_t` is not something you ever actually want, because it is the explicit inverse of a matrix which is extremely unstable. Figure out what you are actually going to be using C_t for (e.g., do you want its square root? it's eigenvalues? linear solves with it? The ability to compute lots of linear solves with it via a decomposition?) and get those directly.

**Comment by Akella17** [comment]
@jacobrgardner This might be a silly doubt, but shouldn't &alpha;<sub>t</sub> be (covar_x + &sigma;<sup>2</sup>I).inv_matmul(train_y). Or does it numerically not make a significant difference?

```covar_x.inv_matmul(train_y)``` computation can be efficient for a good choice of covariance function but (covar_x + &sigma;<sup>2</sup>I).inv_matmul(train_y) does not seem that straight forward.

**Comment by gpleiss** [comment]
@Akella17 - you're right about (covar_x + σ2I).inv_matmul(train_y) - you could do `likelihood(model(train_x)).lazy_covariance_matrix.inv_matmul(train_y)`.

You're also right that you don't nee the additive structure over the linear kernel - just over the RBF kernel.

**Comment by Akella17** [comment]
Hey, thanks for the clarification!!
