### ISSUE TITLE
parameters and functions (inherited torch.autograd.Function) / freezing of parameters

### ISSUE THREAD

**Issue by cherepanovic** [cornellius-gp/gpytorch#773]
- for example a given example below, how to distinguish which attributes are parameters and which are the backward functions, since both are in __init__ and in forward.

- how to freeze the GP parameters, for example the mean or the cov? 

```
class ExactGPModel(gpytorch.models.ExactGP):
    def __init__(self, train_x, train_y, likelihood):
        super(ExactGPModel, self).__init__(train_x, train_y, likelihood)
        self.mean_module = gpytorch.means.ZeroMean()
        matern = gpytorch.kernels.MaternKernel(
            nu=2.5,
            lengthscale_prior=gpytorch.priors.NormalPrior(1, .001)
        )
        self.covar_module = matern

    def forward(self, x):
        mean_x = self.mean_module(x)
        covar_x = self.covar_module(x)
        return gpytorch.distributions.MultivariateNormal(mean_x, covar_x)
```

**Comment by jacobrgardner** [comment]
Only things defined as `torch.nn.Parameters` in a `torch.nn.Module` are parameters that get optimized. You can view all of the things that satisfy this criteria using `model.named_parameters().` For example: `print(list(model.named_parameters()))`.

For any particular parameter, you can either set `param.requires_grad = False` (for example, `model.covar_module.raw_lengthscale.requires_grad = False`), or note that torch optimizers only optimize the parameters that are passed to them. Therefore, you can pass a subset of parameters to e.g. `torch.optim.Adam` when you construct it and only that subset will get optimized.

In general, because all GPyTorch models are just torch Modules, parameter handling like this functions the same way it does in standard PyTorch, so I'd recommend any of the great PyTorch tutorials available on the topic.

**Comment by cherepanovic** [comment]
iteration of that model gives

```
likelihood.noise_covar.raw_noise
Parameter containing:
tensor([0.], requires_grad=True)
covar_module.raw_lengthscale
Parameter containing:
tensor([[0.]], requires_grad=True)
```

**Comment by cherepanovic** [comment]
close
