### ISSUE TITLE
predictive equations in code

### ISSUE THREAD

**Issue by cherepanovic** [cornellius-gp/gpytorch#786]
I am looking for these equations in the code. 

![rw2](https://user-images.githubusercontent.com/10064548/61186831-2c362180-a66a-11e9-9ef9-fad100d92a0e.png)

I suppose it should be somewhere in distribution classes however need your support, thanks!

the picture is taken from:
C. E. Rasmussen & C. K. I. Williams, Gaussian Processes for Machine Learning, the MIT Press, 2006

**Comment by cherepanovic** [comment]
exact_prediction_strategies.py

**Comment by cherepanovic** [comment]
Unfortunately, I have problems in comprehension of the calculation of the predictive distribution. I simply struggle how **2.23** and **2.24** from the picture above will be calculated.

for the posterior distributions following methods will be called: 
https://github.com/cornellius-gp/gpytorch/blob/14c043754540351fb024f20746ddc66b434642ed/gpytorch/models/exact_prediction_strategies.py#L321

and 

https://github.com/cornellius-gp/gpytorch/blob/14c043754540351fb024f20746ddc66b434642ed/gpytorch/models/exact_prediction_strategies.py#L301

in my experiment following parts of this class are involved: 

https://github.com/cornellius-gp/gpytorch/blob/14c043754540351fb024f20746ddc66b434642ed/gpytorch/models/exact_prediction_strategies.py#L339-L344

https://github.com/cornellius-gp/gpytorch/blob/14c043754540351fb024f20746ddc66b434642ed/gpytorch/models/exact_prediction_strategies.py#L352-L355


my GP-model is:

```
class ExactGPModel(gpytorch.models.ExactGP):
    def __init__(self, train_x, train_y, likelihood):
        super(ExactGPModel, self).__init__(train_x, train_y, likelihood)
        self.mean_module = gpytorch.means.ZeroMean()
        matern = gpytorch.kernels.ScaleKernel(gpytorch.kernels.RBFKernel())
        self.covar_module = matern

    def forward(self, x):
        mean_x = self.mean_module(x)
        covar_x = self.covar_module(x)
        return gpytorch.distributions.MultivariateNormal(mean_x, covar_x)

model = ExactGPModel(
    torch.tensor(train_x).float(),
    torch.tensor(train_y).float(),
    gpytorch.likelihoods.GaussianLikelihood()
)
model.eval()
```

I use it without any training.

next question is how can I manipulate σ²I in 2.23 and 2.24 equation in the code? 

Thanks a lot!

**Comment by jacobrgardner** [comment]
`(K(X, X) + s^2 I)^{-1}(y - \mu_0)` is computed here:
https://github.com/cornellius-gp/gpytorch/blob/14c043754540351fb024f20746ddc66b434642ed/gpytorch/models/exact_prediction_strategies.py#L268-L269

and then the rest of the predictive mean (2.23) is computed here:
https://github.com/cornellius-gp/gpytorch/blob/14c043754540351fb024f20746ddc66b434642ed/gpytorch/models/exact_prediction_strategies.py#L313-L318

The covariance is a little more complicated, because we have a `gpytorch.settings.fast_pred_var` option that uses [this paper](https://arxiv.org/pdf/1803.06058.pdf). However, with `fast_pred_var` off the relevant code is here:
https://github.com/cornellius-gp/gpytorch/blob/14c043754540351fb024f20746ddc66b434642ed/gpytorch/models/exact_prediction_strategies.py#L348-L360

If you want to modifiy the noise term, that exists in the likelihood. For example:
```python
likelihood = gpytorch.likelihoods.GaussianLikelihood()
likelihood.noise = 3.  # set \sigma^{2} = 3
likelihood.noise_model.raw_noise.requires_grad = False  # Fix the noise, i.e. make it untrainable by the pytorch optimizer.
```
