### ISSUE TITLE
Is there a way to skip mean calculation since I only need covariance?

### ISSUE THREAD

**Issue by mejliu** [cornellius-gp/gpytorch#789]
Sorry to open this issue. I have searched `settings.py`, and it seems like there is not way to only compute variance while skip mean calculation. Or, on the contrary, is there a way to skip covariance calculation while keeping mean calculation. 

Just want to make sure. Thanks.

**Comment by jacobrgardner** [comment]
Yeah, we don't currently have a way to skip the mean computation because we felt that the mean is very cheap compared to the variances (e.g., the variances are `O(t)` times the work with `t` test examples). I suppose we could add an option for this if you think it would make a substantial speed benefit; however, I'll note that once the mean cache is computed (e.g., after the first time you make predictions) everything will be quite fast anyways.

**Comment by mejliu** [comment]
Yes. you are right. Mean is very cheap to compute. I guess there is no need to add this option. Thanks for your reply.
