### ISSUE TITLE
get_fantasy_model for multi-task GPs

### ISSUE THREAD

**Issue by eytan** [cornellius-gp/gpytorch#800]
# 🚀 Feature Request

I would like to be able to use `get_fantasy_model()` with a GP model that includes derivative observations (along the lines of the GPModelWithDerivatives) tutorial notebook.  However, when I try to do this, I get the following error:

```
RuntimeError: Cannot yet add fantasy observations to multitask GPs, but this is coming soon!
```

Is support for multi-task GPs coming soon?  I know that @Balandat has implemented them for the specific case of IndependentModelList models, but it doesn't appear that there has been more general development for other types of MTGPs.

## Motivation
Derivative observations have been shown to substantially accelerate Bayesian optimization.  It should be fairly straightforward to plug derivative information into BoTorch if it were possible to get fantasy models for data with derivative observations. 

## Pitch

**Describe the solution you'd like**
Ability to use fantasies with generic multi-task models (or at least, the types of multi-task models you would have when derivative information is available for all observations).

**Describe alternatives you've considered**
None.

**Are you willing to open a pull request?** (We LOVE contributions!!!)
I'm sorry.

**Comment by cahity** [comment]
Hey there!
I see that #805 didn't make it to the merge. Are there any improvements expected?

**Comment by gpleiss** [comment]
@cahity This was a while ago, so I'm not sure. It looks like there were test failures that weren't resolved. 

We would probably want to start the PR from scratch tho (3 years is a long time for code...) would you be willing to revive the PR?

**Comment by cahity** [comment]
I would be happy to contribute, so I will give it a go.
Anyone who beats me to it is more than welcome though.

**Comment by yyexela** [comment]
Hey all! Any update on this?

**Comment by cahity** [comment]
Unfortunately, I didn't have the time. I doubt anyone is working on it, so... I guess no updates for now.

**Comment by yyexela** [comment]
No worries at all! I appreciate the quick reply:)

**Comment by yyexela** [comment]
I would like to implement this, since it's needed as part of my research project, is there any guidance I could get on where to start or what exactly should be implemented? I originally thought I should have my derivative-enabled GP from  subclass `BatchedMultiOutputGPyTorchModel` instead of `GPyTorchModel`, but the documentation for the former says the outputs are independent, which is not the case when working with derivatives. Otherwise, I'm getting an error with `qNoisyExpectedImprovement`: `linalg.cholesky: (Batch element 0): The factorization could not be completed because the input is not positive-definite (the leading minor of order 6 is not positive-definite).` which I'm trying to resolve, but I'm not sure if it's the right direction. Any help is appreciated!

**Comment by yyexela** [comment]
I think this can be closed as well @jacobrgardner
