### ISSUE TITLE
Add simple api for combining kernels

### ISSUE THREAD

**Issue by Balandat** [cornellius-gp/gpytorch#81]
There should be a simple API for combining kernels, which allows concise syntax and a lot of flexibility, while at the same time preventing users from shooting themselves in the foot (e.g. break closure by subtracting kernels, etc).

@darbour has some prototype of this, which defines the appropriate operators on the base Kernel class, e.g.:

```
# in Kernel
    def __add__(self, other):
        return AdditiveKernel(self, other)

class AdditiveKernel(Kernel):
    def __init__(self, kernel_1, kernel_2):
        super(AdditiveKernel, self).__init__()
        self.kernel_1 = kernel_1
        self.kernel_2 = kernel_2

    def forward(self, x1, x2):
        return self.kernel_1(x1, x2) + self.kernel_2(x1, x2)
```

**Comment by jrg365** [comment]
In the current code base, adding kernels would be accomplished by doing something like:
```python
first_covar_module = RBFKernel()
second_covar_module = PeriodicKernel()
covar_x = first_covar_module(x) + second_covar_module(x)
```
Since `gpytorch.lazy.LazyVariable` defines `__add__`, this works even when using things like the `GridInterpolationKernel` for scalable inference, although when using specifically models that decompose over sets of dimensions the preferred method is to just use `AdditiveGridInterpolation`. 

We could define something like `AdditiveKernel` above, and that would allow something like this (assuming we defined `__add__` for the base `Kernel` class):
```python
first_covar_module = RBFKernel()
second_covar_module = PeriodicKernel()
full_covar_module = first_covar_module + second_covar_module
covar_x = full_covar_module(x)
```
Technically, the first pattern would still be possible in this case, so I guess it would be user choice whether they want to add the kernels or add the outputs. Do you have an example use case in mind where the second pattern is better than the first?

**Comment by darbour** [comment]
I think the advantage of being able to add the kernels directly (rather than the LazyVariables) is that it's a bit more explicit / easy to interpret, since we'd define the Additive kernel in the constructor where the component kernels are defined. It's certainly not critical by any stretch, so if you feel like it would clutter or confuse the codebase I'm happy to drop this.

**Comment by jrg365** [comment]
@gpleiss and I just talked about it , and we think having the option could be good, since it doesn't really exclude the first option. It could also make it easier / feasible to use, e.g., `AdditiveGridInterpolationKernel` with a composite base kernel, so it does increase the flexibility of GPyTorch.

Here are two design considerations:

- I would suggest we follow the design of GPy as well as our own `SumLazyVariable` and `MulLazyVariable`. `AdditiveKernel` should be a `Kernel` whose constructor takes a list of base_kernels, and `forward()` adds all of them. The `__add__` method of `Kernel` returns an `AdditiveKernel` so that `covar1 + covar2` returns an `AdditiveKernel` with two components. 

- Right now, if you want to add two kernels that operate on restricted sets of input dimensions, the first pattern I described above would be the only way to accomplish this -- i.e., you'd call `first_covar` on `x[:, first_dims]`, call `second_covar` on `x[:, second_dims]` and sum the results. Should the composite kernels also support this (GPy and GPflow do this via the `active_dims` argument to kernels)? I would lean towards no since this would start cluttering the kernel interfaces, but then the second pattern is strictly less general than the first, and I worry that people might believe that this kind of construction is impossible in GPyTorch if they only see examples of the second pattern rather than the first.

**Comment by darbour** [comment]
Great, I'll have a pull request up this afternoon. The semantics follow your suggestions in the first point for both addition and multiplication. Re: point two, I have a stacked diff that allows for declaring the 'active dimensions' for a kernel in the constructor. Hopefully that is up today as well, but it may take until tomorrow.
