### ISSUE TITLE
[Question] Exploit shared covariance matrix for variance predictions in batch-mode

### ISSUE THREAD

**Issue by befelix** [cornellius-gp/gpytorch#814]
With `gpytorch`'s batch-mode, we can use shared covariance matrices for multiple, independent outputs, e.g., [in this example](https://gpytorch.readthedocs.io/en/latest/examples/04_Scalable_GP_Regression_1D/SVGP_Batch_Regression_1D.html). 

A shared covariance matrix should also allow us to do variance predictions faster, since the predictive variance is the same for all outputs and only the mean predictions differ. Is there a way to exploit this within `gpytorch`?

As far as I can tell the batch-mode examples compute variance predictions for each output dimension individually.

All the best,
Felix

**Comment by jacobrgardner** [comment]
In general we don't currently take advantage of that for the simple reason that, while you're right the variances will be identical if you use the same kernel, GPyTorch also supports having kernels themselves operate in batch mode.

For example, `RBFKernel(batch_shape=torch.Size([5]), ard_num_dims=3)` will actually learn a full `5 x 3` matrix of lengthscales -- `3` lengthscales for each dimensions, and separate lengthscales for the different output GPs.

In order to make the optimization you're talking about, we'd have to know that the user's model didn't specify any batch shapes in their model that would affect the kernels for each of the different outputs. This *might* be possible to detect?

**Comment by gpleiss** [comment]
@jacobrgardner - this wouldn't be too difficult to implement for exact GPs. For variational GPs, it would also be possible though the interface would be a bit clunkier (we would have to specify that `CholeskyVariationalDistribution` should be batch for mean parameters, but non-batch for covariance parameters).

As far as I can tell, the use case I see for this is when you are doing independent multi-task predicti9nos. However, in that case it might be the most ideal model, since your variances would only be based on the input data and not on the specific output.

@befelix - do you have a specific use-case where you want this? From a modeling perspective, I think it would be beneficial to do what @jacobrgardner suggests -- `RBFKernel(batch_shape=torch.Size([5]), ard_num_dims=3)` -- so that you get more interesting variances. Also, though this is more computation, GPyTorch is very batch efficient (especially with GPUs) so it probably won't make much of a difference in practice.

**Comment by befelix** [comment]
Our use case would be mostly in time-series latent variable models, where we predict multi-dimensional time series by forward-sampling from the GP model using the re-parametrization trick. These are typically small models with inducing points - so that they generally use the cholesky decomposition. Without sharing the kernel matrix, we often run into memory issues on GPUs and often there's not much being lost in terms of generality when normalizing the data appropriately.

Of course I would understand if there is no plan to include this into the library, since it's a somewhat specialized usecase.

**Comment by gpleiss** [comment]
This actually shouldn't be too difficult to implement - and sounds like it could save memory. Are you using exact GPs or variational GPs?

**Comment by gpleiss** [comment]
@befelix - I believe that both exact and variational GPs should allow for covariance-matrix sharing (as of #903).
