### ISSUE TITLE
using BBMM for computation of standard error of hyperparameters

### ISSUE THREAD

**Issue by cmlakhan** [cornellius-gp/gpytorch#838]
I apologize for the naive question but I am interested in using your GPyTorch tools for some work in genetics but am unclear whether I can get the standard errors for hyperparameters.  In this situation I have a set N individuals with a phenotype y and X being a matrix of genotypes. I want to know the variance explained by their genetic similarity.  We typically compute a genetic similarity kernel and want to know the variance explained by that particular kernel.  I am basically interested in knowing the estimates of the variance parameters and the standard errors for these variance parameters.  From a cursory reading of (https://arxiv.org/pdf/1809.11165.pdf and https://arxiv.org/abs/1903.08114v1) I kind of get how you would get the variance estimates using your BBMM procedure but it is unclear to me whether your BBMM procedure can also estimate the inverse of the Fisher Information matrix in order to get the standard errors for these hyperparameters (See Appendix D, p.200, of this thesis https://www.ebi.ac.uk/sites/ebi.ac.uk/files/shared/documents/phdtheses/Casale-Thesis.pdf for the formula (equation D.16)).  Is this possible?  I apologize if my question is unclear but can clarify if you are confused.

If this specific way of getting SE estimates is not possible is there any way to estimate the uncertainty of these hyperparameters?

**Comment by jacobrgardner** [comment]
So if you are willing to implement the derivative matrices `dK/d\theta_{n}` yourself, (see e.g. `gpytorch.kernels.RBFKernelGrad`, then it is straight forward to use CG for the solves and trace estimation, you just approximate `Tr(K^{-1}dK/d\theta_{n}K^{-1}dK/d\theta_{n}) = E[z^{T}K^{-1}dK/d\theta_{n}K^{-1}dK/d\theta_{n}z]` as we do for standard traces.

If you don't want to compute the derivatives yourself, things become a little trickier because PyTorch doesn't let you directly materialize full derivative matrices in parallel, and you unfortunately can't write that trace as a simple quadratic form with the derivative `p^{T} dK/d\theta_{n} q` like we do for most of our operations.

I haven't fully thought this through, but the way I might approach approximating this is to observe that the trace in that equation can be related to the squared Frobenius norm, `Tr(K^{-1}dK/d\theta_{n}K^{-1}dK/d\theta_{n}) = ||K^{-1}dK/d\theta_[n}||_{F}^{2}`, and then use a method for approximating the squared Frobenius norm -- for example, `||A||_{F}^{2}` can be related to `E[||Az||_{2}^{2}]`, where `z` is uniformly drawn from the `d` dimensional unit ball (e.g., `y ~ N(0, I), z =  y / ||y||_{2}`).

**Comment by cmlakhan** [comment]
Thanks @jacobrgardner I will need to spend some time reading your papers and understanding your approach but I appreciate the pointers.  If I can figure it out will let you know.
