### ISSUE TITLE
Materializing lazy kernel tensors in SGPR

### ISSUE THREAD

**Issue by sdaulton** [cornellius-gp/gpytorch#860]
I am using an SGPR and noticed that there are many calls to `delazify` in the `InducingPointKernel`. Upon digging deeper, I noticed that in the MLL computation, `output.log_prob(target)` calls `covar.inv_quad_log_det`, which calls `LazyTensor.representation` which materializes all constituent lazy tensors including the K_nm kernel matrix (`n x m` for `n` inputs and `m` inducing points). Is this the expected behavior? This leads to memory limit issues when using a GPU.
cc @Balandat

**Comment by jacobrgardner** [comment]
@sdaulton Yes, materializing `K_{nm}` is intentional (and unavoidable) if you aren't using e.g. a KeOps base kernel.

If you're using a large enough dataset that you are running in to memory issues with an `n x m` matrix, you'll need to switch to using variational inference which allows you to restrict the memory usage to `size of minibatch x m`.
