### ISSUE TITLE
Questions about K_xx in gpytorch 

### ISSUE THREAD

**Issue by cherepanovic** [cornellius-gp/gpytorch#902]
Hello dear community, 

K_xx denotes the matrix containing all pairs of kernel entries [1]. 

![pred](https://user-images.githubusercontent.com/10064548/66843108-9b265d80-ef6c-11e9-9023-15b65e47ae61.png)

In answering in one of my question, I learned that the covariance matrix will not be saved 

>It is not necessary to save the covariance matrix.
from https://github.com/cornellius-gp/gpytorch/issues/815#issuecomment-517680588

I still struggle to understand how the prediction will be done if the K_xx ist not saved. 

Secondly, in such examples as in [2], where train data will be passed batchwise, the covariance matrix K_xx would be always of the size of the current batch (?) (and will also based on this batch). Does have previous K_xx (from the previous batch) any influence on the K_xx of the next batch? How will the "end" K_xx be constructed and which dimension would it have?   

[1] - PyTorch: Blackbox Matrix-Matrix GaussianProcess Inference with GPU Acceleration; https://arxiv.org/pdf/1809.11165.pd
[2] - https://gpytorch.readthedocs.io/en/latest/examples/08_Deep_Kernel_Learning/Deep_Kernel_Learning_DenseNet_CIFAR_Tutorial.html

I really hope, that your answer solves all my misunderstandings, thanks

**Comment by gpleiss** [comment]
Regarding 1: Saving an `gpytorch.models.ExactGP` stores the model's hyperparameters as well as the training data. To see this for yourself, examine the contents of `model.state_dict()`, where model is an ExactGP model. You should see everything that GPyTorch saves when it saves a model.

This is all the information you need to then produce predictions. At test time we compute the covariance matrix `K_{XX}` (using the training data we have saved), and then compute fast caching terms which allow us to compute the two terms in (1) in linear or constant time. See [this paper](https://arxiv.org/abs/1803.06058) for details on the caching strategy.

(We do have plans to store these cache terms as part of the state dict.)

Regarding 2: Stochastic variational models, such as the one you linked to, use a different set of equations for inference. This is because these models are performing variational inference and not exact inference (which is the only case discussed in [1]). Though the data change from minibatch to minibatch, the inducing points stay constant. See [this paper](http://proceedings.mlr.press/v38/hensman15.pdf) for more details on variational GP inference.

**Comment by DanielH1994** [comment]
> Regarding 1: Saving an `gpytorch.models.ExactGP` stores the model's hyperparameters as well as the training data. To see this for yourself, examine the contents of `model.state_dict()`, where model is an ExactGP model. You should see everything that GPyTorch saves when it saves a model.
> 
> This is all the information you need to then produce predictions. At test time we compute the covariance matrix `K_{XX}` (using the training data we have saved), and then compute fast caching terms which allow us to compute the two terms in (1) in linear or constant time. See [this paper](https://arxiv.org/abs/1803.06058) for details on the caching strategy.
> 
> (We do have plans to store these cache terms as part of the state dict.)
> 
> Regarding 2: Stochastic variational models, such as the one you linked to, use a different set of equations for inference. This is because these models are performing variational inference and not exact inference (which is the only case discussed in [1]). Though the data change from minibatch to minibatch, the inducing points stay constant. See [this paper](http://proceedings.mlr.press/v38/hensman15.pdf) for more details on variational GP inference.

Hi, @gpleiss . Has the application of saving the cache terms into the state dict been realized now? 
In my Batch Independent multitask GP with 47 outputs, 1500 training points and the input dimension is 31, after I reload the model, the prediction for the first test takes more than 20 seconds but for the second one it takes only 0.02s. I think this time must be consumed in computing the 47 `K_{XX}` and their inverses for each output and it is very expensive (`O(47 \times 1500^3)`).  Is there any way to save them for the later predictions?

**Comment by gpleiss** [comment]
Currently this has not been solved. There are some issues with the caches that need to be worked out.
