### ISSUE TITLE
[uncertainty propagation of  input  through GP]

### ISSUE THREAD

**Issue by aimanian** [cornellius-gp/gpytorch#913]
# 🚀 Feature Request

Hello, 

Can you please let me any of regression model which is able to propagate the uncertainty of the input.

Thanks,
Anahita

**Comment by gpleiss** [comment]
What form do your input uncertainties take? None of our models explicitly support this, but I bet you could accomplish this pretty easily with [one of our variational inference models](https://gpytorch.readthedocs.io/en/latest/examples/04_Scalable_GP_Regression_1D/SVGP_Regression_1D.html).

Here's an example: assume that `train_x` comes from a normal distribution -- i.e. `train_x = torch.distributions.Normal(train_x_mean, train_x_std)`. During learning, you could then draw samples from this distribution. Something like this (code taken from the linked example above):

```python
    # Training loop
    for i in range(num_iter):
        optimizer.zero_grad()
        # Draw samples from the input distribution
        train_x = torch.distributions.Normal(train_x_mean, train_x_std).sample()
        output = model(train_x)
        # Calc loss and backprop gradients
        loss = -mll(output, train_y)
        loss.backward()
        optimizer.step()
```

**Comment by jejjohnson** [comment]
Hi, 

I like the method you suggested as it seems very simple. It also seems related to the method suggested in #659. I am doing research regarding input uncertainty and GPs and I had a question:

Is there a formal way to describe something like this in the GP literature? I've seen many things such as moment-matching, linearization or Monte Carlo. Is this some form of pseudo-Monte Carlo? In the sense that we kind of perturb the inputs by some noise and then train the model with the perturbed inputs? Also, do you know of any 'formal' research been done on this? 

Thanks!

**Comment by aimanian** [comment]
Thanks, for your reply!
I had a little study on the  Gaussian process latent variable models.
So, I think your suggestion is based on the embedded assumption of the model where it considers the distribution for inputs.

Thanks,
Anahita

**Comment by gpleiss** [comment]
@jejjohnson - These are some relevant papers.

https://papers.nips.cc/paper/2313-gaussian-process-priors-with-uncertain-inputs-application-to-multiple-step-ahead-time-series-forecasting
http://papers.nips.cc/paper/4295-gaussian-process-training-with-input-noise
http://www.jmlr.org/papers/volume17/damianou16a/damianou16a.pdf (e.g. section 6.2)

This can be thought of as a monte carlo method to some extent. Using VI, our objective function is
```
E_{x} E_{q(f(x))} [ log p(y | f(x) ] - KL.
```
Since we are using stochastic optimization, we can draw samples from x to compute an unbiased estimate of the log-likelihood term.

**Comment by jejjohnson** [comment]
@gpleiss Thank you for the explanation. I think I understand now. Again, it’s a very practical and neat trick!

**Comment by gpleiss** [comment]
Sounds like we need an example for this. I'm going to collapse this issue and #659 into a different issue.

**Comment by cisprague** [comment]
@gpleiss @jejjohnson — I am trying to model a large-scale 2D field with an SVGP `f: (x,y) -> z`, where each input `(x,y)_i` has it's own distribution `N(0, Σ_i)`. Further, the input distributions are correlated with each other since they come from vehicle dead-reckoning. In this case, would there be an issue with using the input distribution sampling method shown above? Could you recommend some things to look at in the literature? Thank you!
