### ISSUE TITLE
[Docs] grid_bounds and grid_size parameters in AdditiveGridInterpolationVariationalStrategy

### ISSUE THREAD

**Issue by cherepanovic** [cornellius-gp/gpytorch#950]
What it the best way to analyse and to set these parameters (`grid_bounds`, `grid_size`parameters) for particular dataset, are there any heuristics?

**Comment by gpleiss** [comment]
grid_size = gpytorch.utils.grid.choose_grid_size(train_x,1.0)

See https://gpytorch.readthedocs.io/en/latest/examples/04_Scalable_GP_Regression_1D/KISSGP_Regression_1D.html for an example

**Comment by cherepanovic** [comment]
@gpleiss 

> If you want, you can also explicitly determine the grid bounds of the SKI approximation using the grid_bounds argument. However, it’s easier if you don’t use this argument - then GPyTorch automatically chooses the best bounds for you.

> https://gpytorch.readthedocs.io/en/latest/examples/04_Scalable_GP_Regression_1D/KISSGP_Regression_1D.html

grid_bounds is a necessary parameter for AdditiveGridInterpolationVariationalStrategy.

**Comment by cherepanovic** [comment]
I am speaking about this outdated configuration in GPLayer

```
class GaussianProcessLayer(gpytorch.models.AbstractVariationalGP):
    def __init__(self, num_dim, grid_bounds=(-10., 10.), grid_size=64):
        variational_distribution = gpytorch.variational.CholeskyVariationalDistribution(
            num_inducing_points=grid_size, batch_size=num_dim
        )
        variational_strategy = gpytorch.variational.AdditiveGridInterpolationVariationalStrategy(
            self, grid_size=grid_size, grid_bounds=[grid_bounds], num_dim=num_dim,
            variational_distribution=variational_distribution, mixing_params=False, sum_output=False
        )
        super().__init__(variational_strategy)

        self.covar_module = gpytorch.kernels.ScaleKernel(
            gpytorch.kernels.RBFKernel(
                lengthscale_prior=gpytorch.priors.SmoothedBoxPrior(
                    math.exp(-1), math.exp(1), sigma=0.1, transform=torch.exp
                )
            )
        )
        self.mean_module = gpytorch.means.ConstantMean()
        self.grid_bounds = grid_bounds

```

**Comment by gpleiss** [comment]
AdditiveGridInterpolationVariationalStrategy is deprecated and will be removed shortly. The DKL example will also be updated shortly.

In general, the grid bounds need to completely enclose your data. Since the data is the output of a neural network - you have to transform the NN output to be within some bounds. That's what the scale to bounds helper does.

The grid size can be anything. For the variational example, the running time is quadratic in the number of grid points. The larger you can make it the better (before it starts becoming too slow).
