### ISSUE TITLE
[Bug] probe_vectors should NOT be unit norm functions/_inv_quad_log_det.py?

### ISSUE THREAD

**Issue by joacorapela** [cornellius-gp/gpytorch#952]
# 🐛 Bug

In functions/_inv_quad_log_det.py I see that probe_vectors are set to unit
norm:

>             probe_vectors = probe_vectors.div(probe_vector_norms)

and, as I show below, I think this is a mistake.

As in page 4 of Gardner et al, 2018, suppose I want to estimate the trace of
the identity matrix I_m in R^m and that A is an invertible matrix in R^{nxn}.
Then:

Tr(I_m) = Tr(AxA^{-1}) ~ 1/t \sum_{i=1}^t z_i^T A A^{-1} z_i =
                       = 1/t \sum_{i=1}^t z_i^T z_i = (because z_i unit norm)
                       = 1/t \sum_{i=1}^t 1 = 1

But Tr(I_m) equals m.

**Comment by joacorapela** [comment]
In the first line after Equation r in Gardner et al., 2018 it says:
"is an unbiased estimation of the derivative." but I guess it should say "is an unbiased estimation of the trace." Correct? or am I missing something?

**Comment by jacobrgardner** [comment]
@joacorapela It's so that the projection of the probe vector on to the Krylov subspace Q'z is e_1 rather than ||z||e_1. See e.g. algorithm 1 [here](https://www-users.cs.umn.edu/~saad/PDF/ys-2016-04.pdf). Note that in the backward pass we remultiply by the probe vector norm because there we directly do a trace estimate and need the vectors unnormalized:
https://github.com/cornellius-gp/gpytorch/blob/6ecd398f815702bec9b8a895bed85da26293fa63/gpytorch/functions/_inv_quad_log_det.py#L186-L187

Both the trace estimate and the gradient estimate are unbiased, so I suppose either would work there.
